import { getCurrentUser } from "../../../lib/auth";
import { writeAuditEvent } from "../../../lib/audit";
import { activeJuniorGoldSql, activeJuniorGoldValues, calculateJuniorGoldEligibility, ensureJuniorGoldSchema, hasJuniorGoldPermission, JUNIOR_GOLD_PROFILE, mayManageJuniorGold, memberIdForUser, validateJuniorGoldTemplate } from "../../../lib/junior-gold";
import { AWA_JR01_COORDINATES, generateJuniorGoldPdf, type JuniorGoldImage, type JuniorGoldMark, type JuniorGoldText } from "../../../lib/junior-gold-pdf";
import { presidentsBadgeRuntime, releasePrivateDocument, reservePrivateDocument, sha256Bytes, validateOverlayText } from "../../../lib/presidents-badge";

export const runtime="edge";export const dynamic="force-dynamic";
const headers={"Cache-Control":"private, no-store"};const json=(body:unknown,init:ResponseInit={})=>Response.json(body,{...init,headers:{...headers,...(init.headers??{})}});const now=()=>new Date().toISOString();const asId=(value:unknown)=>Number.parseInt(String(value??"0"),10);

async function bucket(){if(!presidentsBadgeRuntime.DOCUMENTS)throw new Error("Private R2 document storage is unavailable. Redeploy with the DOCUMENTS binding.");return presidentsBadgeRuntime.DOCUMENTS;}
async function store(prefix:string,bytes:Uint8Array,contentType:string){const r2=await bucket();await reservePrivateDocument(bytes.byteLength);const hash=await sha256Bytes(bytes);const key=`junior-gold/${prefix}/${crypto.randomUUID()}`;try{await r2.put(key,bytes,{httpMetadata:{contentType},customMetadata:{sha256:hash}});}catch(error){await releasePrivateDocument(bytes.byteLength);throw error;}return{key,hash};}
function imageType(file:File,bytes:Uint8Array){if(file.size<20||file.size>5*1024*1024)throw new Error("Image must be 5 MB or smaller.");const png=bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47;const jpeg=bytes[0]===0xff&&bytes[1]===0xd8&&bytes.at(-2)===0xff&&bytes.at(-1)===0xd9;if(file.type==="image/png"&&png)return"image/png" as const;if(file.type==="image/jpeg"&&jpeg)return"image/jpeg" as const;throw new Error("Use a genuine PNG or JPEG image.");}
async function access(user:NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>,id:number){const row=await presidentsBadgeRuntime.DB.prepare(`SELECT a.*,m.email member_email FROM junior_gold_applications a JOIN members m ON m.id=a.member_id WHERE a.id=?`).bind(id).first<Record<string,string|number|null>>();if(!row)return null;const own=String(row.member_email).toLowerCase()===user.email.toLowerCase();if(!own&&!mayManageJuniorGold(user)&&!hasJuniorGoldPermission(user,"junior_gold.view_sensitive"))return null;return{row,own};}
const splitPhone=(value:string)=>{const digits=value.replace(/\D/g,"");return{area:digits.slice(0,3),number:digits.slice(3,13)}};
const dateParts=(page:number,x:number,y:number,value:string,size=7):JuniorGoldText[]=>{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);return m?[{page,x,y,value:m[3],max:2,size},{page,x:x+38,y,value:m[2],max:2,size},{page,x:x+80,y,value:m[1],max:4,size}]:[];};

export async function GET(request:Request){await ensureJuniorGoldSchema();const user=await getCurrentUser(request);if(!user)return json({error:"Sign in required"},{status:401});const url=new URL(request.url);const id=asId(url.searchParams.get("applicationId"));const canManage=mayManageJuniorGold(user);const ownId=await memberIdForUser(user);
  if(id){const allowed=await access(user,id);if(!allowed)return json({error:"Application not found or access is not permitted"},{status:404});const [member,versions,outcomes,officers]=await Promise.all([
    presidentsBadgeRuntime.DB.prepare(`SELECT id,name,rank,squad,section,email,gender,contact_number,nric,birth_date,passport_photo_object_key FROM members WHERE id=?`).bind(allowed.row.member_id).first(),
    presidentsBadgeRuntime.DB.prepare("SELECT id,version_number,sha256,created_at,superseded_at FROM junior_gold_versions WHERE application_id=? ORDER BY version_number DESC").bind(id).all(),
    presidentsBadgeRuntime.DB.prepare("SELECT * FROM junior_gold_outcomes WHERE application_id=? ORDER BY id DESC").bind(id).all(),
    presidentsBadgeRuntime.DB.prepare("SELECT id,name,email,officer_rank,contact_number FROM users WHERE active=1 AND role IN ('admin','officer') ORDER BY name").all(),
  ]);return json({application:allowed.row,member,versions:versions.results,outcomes:outcomes.results,officers:officers.results,eligibility:await calculateJuniorGoldEligibility(Number(allowed.row.member_id),Number(allowed.row.application_year),String(allowed.row.exco_meeting_date??""),Boolean(allowed.row.project_completed)),permissions:{canManage,canTemplate:hasJuniorGoldPermission(user,"junior_gold.template"),canOutcome:hasJuniorGoldPermission(user,"junior_gold.outcome")},r2Available:Boolean(presidentsBadgeRuntime.DOCUMENTS)});}
  const stmt=presidentsBadgeRuntime.DB.prepare(`SELECT a.id,a.member_id,a.status,a.application_year,a.updated_at,m.name member_name,m.rank,m.section FROM junior_gold_applications a JOIN members m ON m.id=a.member_id WHERE ${canManage?"1=1":"LOWER(m.email)=LOWER(?)"} ORDER BY a.updated_at DESC`);const applications=canManage?await stmt.all():await stmt.bind(user.email).all();const members=canManage?await presidentsBadgeRuntime.DB.prepare("SELECT id,name,rank,squad,section,email FROM members WHERE section IN ('junior','senior') ORDER BY section,name").all():{results:ownId?(await presidentsBadgeRuntime.DB.prepare("SELECT id,name,rank,squad,section,email FROM members WHERE id=?").bind(ownId).all()).results:[]};const template=await presidentsBadgeRuntime.DB.prepare("SELECT id,form_code,sha256,file_size,page_count,created_at FROM junior_gold_templates WHERE active=1 ORDER BY id DESC LIMIT 1").first();const settings=await presidentsBadgeRuntime.DB.prepare("SELECT * FROM presidents_badge_settings WHERE id=1").first();return json({applications:applications.results,members:members.results,template,settings,profile:JUNIOR_GOLD_PROFILE,r2Available:Boolean(presidentsBadgeRuntime.DOCUMENTS),permissions:{canManage,canTemplate:hasJuniorGoldPermission(user,"junior_gold.template"),canOutcome:hasJuniorGoldPermission(user,"junior_gold.outcome")}});
}

export async function POST(request:Request){await ensureJuniorGoldSchema();const user=await getCurrentUser(request);if(!user)return json({error:"Sign in required"},{status:401});try{
  if(request.headers.get("content-type")?.includes("multipart/form-data")){const form=await request.formData();const action=String(form.get("action")??"");const file=form.get("file");if(!(file instanceof File))throw new Error("Choose a file first.");const bytes=new Uint8Array(await file.arrayBuffer());
    if(action==="upload_template"){if(!hasJuniorGoldPermission(user,"junior_gold.template"))return json({error:"Administrator access required"},{status:403});const checked=await validateJuniorGoldTemplate(bytes);const saved=await store("templates",bytes,"application/pdf");await presidentsBadgeRuntime.DB.prepare("UPDATE junior_gold_templates SET active=0 WHERE layout_profile=?").bind(JUNIOR_GOLD_PROFILE.id).run();await presidentsBadgeRuntime.DB.prepare(`INSERT INTO junior_gold_templates(layout_profile,form_code,object_key,sha256,file_size,page_count,active,uploaded_by_user_id,created_at) VALUES(?,?,?,?,?,?,1,?,?) ON CONFLICT(layout_profile,sha256) DO UPDATE SET object_key=excluded.object_key,active=1,uploaded_by_user_id=excluded.uploaded_by_user_id,created_at=excluded.created_at`).bind(JUNIOR_GOLD_PROFILE.id,JUNIOR_GOLD_PROFILE.formCode,saved.key,saved.hash,bytes.byteLength,checked.pageCount,user.id,now()).run();await writeAuditEvent({actor:user,action:"junior_gold.template_uploaded",entityType:"junior_gold_template",after:{sha256:saved.hash}});return json({ok:true});}
    if(action==="upload_photo"){const memberId=asId(form.get("memberId"));if(memberId!==await memberIdForUser(user)&&!mayManageJuniorGold(user))return json({error:"Permission denied"},{status:403});const contentType=imageType(file,bytes);const saved=await store(`members/${memberId}/photo`,bytes,contentType);await presidentsBadgeRuntime.DB.prepare("UPDATE members SET passport_photo_object_key=? WHERE id=?").bind(saved.key,memberId).run();await writeAuditEvent({actor:user,action:"member.passport_photo_updated",entityType:"member",entityId:memberId,after:{sha256:saved.hash}});return json({ok:true});}
    if(action==="upload_signature"){if(!mayManageJuniorGold(user))return json({error:"Officer access required"},{status:403});const contentType=imageType(file,bytes);const saved=await store(`staff/${user.id}/signature`,bytes,contentType);await presidentsBadgeRuntime.DB.prepare("INSERT INTO staff_signature_profiles(user_id,object_key,sha256,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET object_key=excluded.object_key,sha256=excluded.sha256,updated_at=excluded.updated_at").bind(user.id,saved.key,saved.hash,now()).run();return json({ok:true});}
    if(action==="upload_stamp"){if(user.role!=="admin")return json({error:"Administrator access required"},{status:403});const contentType=imageType(file,bytes);const saved=await store("company/stamp",bytes,contentType);await presidentsBadgeRuntime.DB.prepare("INSERT INTO presidents_badge_settings(id,company_stamp_object_key,updated_by_user_id,updated_at) VALUES(1,?,?,?) ON CONFLICT(id) DO UPDATE SET company_stamp_object_key=excluded.company_stamp_object_key,updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at").bind(saved.key,user.id,now()).run();return json({ok:true});}
    throw new Error("Unknown upload action.");
  }
  const body=await request.json() as Record<string,unknown>;const action=String(body.action??"");
  if(action==="create"){const ownId=await memberIdForUser(user);const memberId=asId(body.memberId||ownId);if(!memberId||(memberId!==ownId&&!mayManageJuniorGold(user)))return json({error:"Permission denied"},{status:403});const existing=await presidentsBadgeRuntime.DB.prepare(`SELECT id FROM junior_gold_applications WHERE member_id=? AND status IN (${activeJuniorGoldSql()}) LIMIT 1`).bind(memberId,...activeJuniorGoldValues()).first<{id:number}>();if(existing)return json({error:"This member already has an active Junior Gold Award application.",applicationId:existing.id},{status:409});const template=await presidentsBadgeRuntime.DB.prepare("SELECT id FROM junior_gold_templates WHERE active=1 ORDER BY id DESC LIMIT 1").first<{id:number}>();const created=now();const status=mayManageJuniorGold(user)?"preparing":"requested";const result=await presidentsBadgeRuntime.DB.prepare(`INSERT INTO junior_gold_applications(member_id,status,application_year,owner_user_id,template_id,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).bind(memberId,status,new Date().getFullYear(),mayManageJuniorGold(user)?user.id:null,template?.id??null,user.id,created,created).run();const id=Number(result.meta.last_row_id);await writeAuditEvent({actor:user,action:"junior_gold.application_created",entityType:"junior_gold_application",entityId:id,after:{memberId,status}});return json({ok:true,applicationId:id});}
  if(action==="save_settings"){if(!mayManageJuniorGold(user))return json({error:"Officer access required"},{status:403});const number=validateOverlayText(String(body.companyNumber??""),"Company number",12),name=validateOverlayText(String(body.companyName??""),"Company name",44),state=validateOverlayText(String(body.state??""),"State",30);await presidentsBadgeRuntime.DB.prepare(`INSERT INTO presidents_badge_settings(id,company_number,official_company_name,malaysian_state,updated_by_user_id,updated_at) VALUES(1,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET company_number=excluded.company_number,official_company_name=excluded.official_company_name,malaysian_state=excluded.malaysian_state,updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at`).bind(number,name,state,user.id,now()).run();return json({ok:true});}
  if(action==="save_compliance"){if(!mayManageJuniorGold(user))return json({error:"Officer access required"},{status:403});const year=asId(body.year);if(year<2000||year>2100)throw new Error("Choose a valid reporting year.");await presidentsBadgeRuntime.DB.prepare(`INSERT INTO company_annual_compliance(reporting_year,brigade_dues_date,ros_return_date,statistics_return_date,updated_by_user_id,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(reporting_year) DO UPDATE SET brigade_dues_date=excluded.brigade_dues_date,ros_return_date=excluded.ros_return_date,statistics_return_date=excluded.statistics_return_date,updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at`).bind(year,String(body.brigadeDuesDate??""),String(body.rosReturnDate??""),String(body.statisticsReturnDate??""),user.id,now()).run();return json({ok:true});}
  const id=asId(body.applicationId);const allowed=id?await access(user,id):null;if(id&&!allowed)return json({error:"Application not found or access is not permitted"},{status:404});
  if(action==="delete_application"){if(!allowed||(!allowed.own&&!mayManageJuniorGold(user)))return json({error:"Only the member or an Officer can delete this application"},{status:403});if(["finalised","submitted","approved"].includes(String(allowed.row.status)))throw new Error("Finalised or submitted applications cannot be deleted.");await presidentsBadgeRuntime.DB.prepare("DELETE FROM junior_gold_applications WHERE id=?").bind(id).run();return json({ok:true});}
  if(action==="save_member_details"){if(!allowed)throw new Error("Application required.");const nric=validateOverlayText(String(body.nric??""),"NRIC",20),birthDate=String(body.birthDate??"");if(birthDate&&!/^\d{4}-\d{2}-\d{2}$/.test(birthDate))throw new Error("Enter a valid birth date.");await presidentsBadgeRuntime.DB.prepare("UPDATE members SET nric=?,birth_date=? WHERE id=?").bind(nric,birthDate,allowed.row.member_id).run();return json({ok:true});}
  if(action==="save"){if(!allowed||!mayManageJuniorGold(user))return json({error:"Officer access required"},{status:403});await presidentsBadgeRuntime.DB.prepare(`UPDATE junior_gold_applications SET exco_meeting_date=?,awards_officer_user_id=?,captain_user_id=?,project_completed=?,include_company_stamp=?,notes=?,status='preparing',owner_user_id=COALESCE(owner_user_id,?),updated_at=? WHERE id=? AND status NOT IN ('finalised','submitted','approved')`).bind(String(body.excoMeetingDate??""),asId(body.awardsOfficerId)||null,asId(body.captainId)||null,body.projectCompleted?1:0,body.includeCompanyStamp?1:0,String(body.notes??""),user.id,now(),id).run();return json({ok:true});}
  if(action==="finalise"){if(!allowed||!mayManageJuniorGold(user))return json({error:"Officer access required"},{status:403});const full=await presidentsBadgeRuntime.DB.prepare(`SELECT a.*,m.name,m.rank,m.section,m.gender,m.email candidate_email,m.contact_number candidate_phone,m.nric,m.birth_date,m.passport_photo_object_key,t.object_key template_key,s.company_number,s.official_company_name,s.malaysian_state,s.company_stamp_object_key,ao.name awards_officer_name,ao.email awards_officer_email,ao.officer_rank awards_officer_rank,ao.contact_number awards_officer_phone,c.name captain_name,sp.object_key captain_signature_key FROM junior_gold_applications a JOIN members m ON m.id=a.member_id LEFT JOIN junior_gold_templates t ON t.id=a.template_id LEFT JOIN presidents_badge_settings s ON s.id=1 LEFT JOIN users ao ON ao.id=a.awards_officer_user_id LEFT JOIN users c ON c.id=a.captain_user_id LEFT JOIN staff_signature_profiles sp ON sp.user_id=a.captain_user_id WHERE a.id=?`).bind(id).first<Record<string,string|number|null>>();if(!full?.template_key)throw new Error("Upload the exact official Junior Gold Award PDF first.");const eligibility=await calculateJuniorGoldEligibility(Number(full.member_id),Number(full.application_year),String(full.exco_meeting_date??""),Boolean(full.project_completed));if(!eligibility.eligible)throw new Error("The linked Junior Gold Award eligibility requirements are not complete.");if(!full.company_number||!full.official_company_name||!full.malaysian_state||!full.awards_officer_name||!full.captain_name)throw new Error("Complete company details and select the Awards Officer and Captain.");if(!full.nric||!full.birth_date||!full.passport_photo_object_key)throw new Error("NRIC, birth date and passport photo are required.");const r2=await bucket();const template=await r2.get(String(full.template_key));if(!template)throw new Error("The official template is unavailable.");const text:JuniorGoldText[]=[
      {...AWA_JR01_COORDINATES.companyNumber,value:String(full.company_number)},{...AWA_JR01_COORDINATES.companyName,value:String(full.official_company_name)},{...AWA_JR01_COORDINATES.state,value:String(full.malaysian_state)},{...AWA_JR01_COORDINATES.awardsOfficerName,value:String(full.awards_officer_name)},{...AWA_JR01_COORDINATES.awardsOfficerRank,value:String(full.awards_officer_rank??"")},{...AWA_JR01_COORDINATES.awardsOfficerEmail,value:String(full.awards_officer_email??"")},{...AWA_JR01_COORDINATES.candidateName,value:String(full.name)},{...AWA_JR01_COORDINATES.gender,value:String(full.gender)==="F"?"F":"M"},{...AWA_JR01_COORDINATES.rank,value:String(full.rank)},{...AWA_JR01_COORDINATES.candidateEmail,value:String(full.candidate_email??"")},{...AWA_JR01_COORDINATES.captainName,value:String(full.captain_name)},
    ];const pushPhone=(value:string,areaX:number,numberX:number,y:number)=>{const phone=splitPhone(value);[...phone.area].forEach((digit,index)=>text.push({page:1,x:areaX+index*4.5,y,value:digit,max:1,size:8}));[...phone.number].forEach((digit,index)=>text.push({page:1,x:numberX+index*4.5,y,value:digit,max:1,size:8}));};pushPhone(String(full.awards_officer_phone??""),112,160,521);pushPhone(String(full.candidate_phone??""),112,160,431);
    const nric=String(full.nric).replace(/\D/g,"");if(nric.length!==12)throw new Error("NRIC must contain exactly 12 digits.");text.push({...AWA_JR01_COORDINATES.nricFirst,value:nric.slice(0,6)},{...AWA_JR01_COORDINATES.nricMiddle,value:nric.slice(6,8)},{...AWA_JR01_COORDINATES.nricLast,value:nric.slice(8)});const birth=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(full.birth_date));if(birth)text.push({...AWA_JR01_COORDINATES.birthDateDay,value:birth[3]},{...AWA_JR01_COORDINATES.birthDateMonth,value:birth[2]},{...AWA_JR01_COORDINATES.birthDateYear,value:birth[1]});
    const yearX=[267,327,387,447,507],percentX=[270,330,390,450,513];eligibility.attendanceYears.slice(0,5).reverse().forEach((row,index)=>{text.push({page:1,x:yearX[index],y:386,value:String(row.year),max:4,size:6.5},{page:1,x:percentX[index],y:374,value:String(row.percentage),max:3,size:6.5});});const awardX:Record<string,number>={junior_white:207,junior_green:267,junior_purple:327,junior_blue:387,junior_red:447,junior_silver:507};eligibility.awards.forEach((award)=>text.push({page:1,x:awardX[award.award_code],y:331,value:String(award.awarded_at??"").slice(0,4),max:4,size:6.5}));
    const compliance=await presidentsBadgeRuntime.DB.prepare("SELECT brigade_dues_date,ros_return_date,statistics_return_date FROM company_annual_compliance WHERE reporting_year=?").bind(full.application_year).first<{brigade_dues_date:string;ros_return_date:string;statistics_return_date:string}>();const marks:JuniorGoldMark[]=[690,674,658,642,626,610].map((y)=>({page:1,x:41,y,checked:true,size:8}));if(compliance){for(const [value,y] of [[compliance.brigade_dues_date,228],[compliance.ros_return_date,203],[compliance.statistics_return_date,178]] as const){text.push(...dateParts(1,296,y,value,7));marks.push({page:1,x:57,y,checked:Boolean(value),size:8});}}text.push(...dateParts(1,75,94,now().slice(0,10),7));
    const images:JuniorGoldImage[]=[];const photo=await r2.get(String(full.passport_photo_object_key));if(photo)images.push({...AWA_JR01_COORDINATES.passportPhoto,bytes:new Uint8Array(await photo.arrayBuffer()),mime:photo.httpMetadata?.contentType==="image/png"?"image/png":"image/jpeg"});if(full.captain_signature_key){const sig=await r2.get(String(full.captain_signature_key));if(sig)images.push({page:1,x:42,y:105,width:190,height:28,bytes:new Uint8Array(await sig.arrayBuffer()),mime:sig.httpMetadata?.contentType==="image/png"?"image/png":"image/jpeg"});}if(full.include_company_stamp&&full.company_stamp_object_key){const stamp=await r2.get(String(full.company_stamp_object_key));if(stamp)images.push({page:1,x:400,y:93,width:95,height:55,bytes:new Uint8Array(await stamp.arrayBuffer()),mime:stamp.httpMetadata?.contentType==="image/png"?"image/png":"image/jpeg"});}
    const output=await generateJuniorGoldPdf(new Uint8Array(await template.arrayBuffer()),{text,marks,images});const saved=await store(`applications/${id}/versions`,output,"application/pdf");const next=await presidentsBadgeRuntime.DB.prepare("SELECT COALESCE(MAX(version_number),0)+1 next FROM junior_gold_versions WHERE application_id=?").bind(id).first<{next:number}>();const version=Number(next?.next??1);await presidentsBadgeRuntime.DB.prepare("UPDATE junior_gold_versions SET superseded_at=? WHERE application_id=? AND superseded_at IS NULL").bind(now(),id).run();await presidentsBadgeRuntime.DB.prepare("INSERT INTO junior_gold_versions(application_id,version_number,object_key,sha256,input_snapshot_json,created_by_user_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(id,version,saved.key,saved.hash,JSON.stringify({application:full,eligibility}),user.id,now()).run();await presidentsBadgeRuntime.DB.prepare("UPDATE junior_gold_applications SET status='finalised',finalised_at=?,updated_at=? WHERE id=?").bind(now(),now(),id).run();await writeAuditEvent({actor:user,action:"junior_gold.pdf_finalised",entityType:"junior_gold_application",entityId:id,after:{version,sha256:saved.hash}});return json({ok:true,version});}
  if(action==="reopen"){if(!allowed||!mayManageJuniorGold(user))return json({error:"Officer access required"},{status:403});await presidentsBadgeRuntime.DB.prepare("UPDATE junior_gold_applications SET status='preparing',finalised_at=NULL,updated_at=? WHERE id=?").bind(now(),id).run();return json({ok:true});}
  if(action==="mark_submitted"){if(!allowed||!mayManageJuniorGold(user))return json({error:"Officer access required"},{status:403});await presidentsBadgeRuntime.DB.prepare("UPDATE junior_gold_applications SET status='submitted',submitted_at=?,updated_at=? WHERE id=? AND status='finalised'").bind(now(),now(),id).run();return json({ok:true});}
  if(action==="record_outcome"){if(!allowed||!hasJuniorGoldPermission(user,"junior_gold.outcome"))return json({error:"Outcome permission required"},{status:403});const outcome=String(body.outcome??""),date=String(body.outcomeDate??""),confirmed=Boolean(body.confirmed);if(!["returned","approved","rejected"].includes(outcome)||!date)throw new Error("Choose a valid outcome and date.");if(outcome==="approved"&&(!confirmed||!String(body.reference??"").trim()))throw new Error("BBM approval requires confirmation and a reference.");await presidentsBadgeRuntime.DB.prepare("INSERT INTO junior_gold_outcomes(application_id,outcome,outcome_date,reference,confirmed_external_decision,notes,recorded_by_user_id,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(id,outcome,date,String(body.reference??""),confirmed?1:0,String(body.notes??""),user.id,now()).run();await presidentsBadgeRuntime.DB.prepare("UPDATE junior_gold_applications SET status=?,closed_at=?,updated_at=? WHERE id=?").bind(outcome,["approved","rejected"].includes(outcome)?now():null,now(),id).run();if(outcome==="approved"&&confirmed)await presidentsBadgeRuntime.DB.prepare(`INSERT INTO member_awards(member_id,award_code,level,status,awarded_at,updated_at,updated_by) VALUES(?,'gold_award','basic','awarded',?,?,?) ON CONFLICT(member_id,award_code,level) DO UPDATE SET status='awarded',awarded_at=excluded.awarded_at,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(allowed.row.member_id,date,now(),user.email).run();return json({ok:true});}
  throw new Error("Unknown Junior Gold Award action.");
 }catch(error){return json({error:error instanceof Error?error.message:"Unable to complete the request"},{status:400});}}
