UPDATE members
SET school = 'ST JOSEPH''S PRIVATE SECONDARY SCHOOL'
WHERE UPPER(TRIM(school)) IN (
  'ST JOSEPH PRIVATE SECONDARY SCHOOL',
  'ST. JOSEPH PRIVATE SECONDARY SCHOOL',
  'ST JOSEPH''S PRIVATE SECONDARY SCHOOL',
  'ST. JOSEPH''S PRIVATE SECONDARY SCHOOL'
);
