"use client";

import { FormEvent, useEffect, useState } from "react";
import { defaultBranding, type Branding } from "./BrandingContext";

export default function BrandingSettings() {
  const [branding, setBranding] = useState<Branding>(defaultBranding);
  const [logoDataUrl, setLogoDataUrl] = useState<string | null>(null);
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/branding", { cache: "no-store" }).then((response) => response.json()).then(setBranding).catch(() => setError("Unable to load app branding.")); }, []);
  function chooseLogo(file?: File) { if (!file) return setLogoDataUrl(null); if (file.size > 750_000) return setError("Choose a logo smaller than 750 KB."); const reader = new FileReader(); reader.onload = () => setLogoDataUrl(String(reader.result)); reader.readAsDataURL(file); }
  async function update(payload: Record<string, unknown>) { const response = await fetch("/api/branding", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { error?: string; message?: string; branding?: Branding }; if (!response.ok) throw new Error(result.error ?? "Unable to update app branding."); if (result.branding) setBranding(result.branding); setLogoDataUrl(null); setNotice(result.message ?? "App branding updated."); window.dispatchEvent(new Event("app-branding-updated")); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); const form = new FormData(event.currentTarget); try { await update({ appName: form.get("appName"), shortName: form.get("shortName"), companyName: form.get("companyName"), subtitle: form.get("subtitle"), logoDataUrl }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update app branding."); } finally { setBusy(false); } }
  async function restoreLogo() { setBusy(true); setError(""); setNotice(""); try { await update({ ...branding, removeLogo: true }); setNotice("Standard BB logo restored."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to restore the standard BB logo."); } finally { setBusy(false); } }
  return <section className="branding-settings"><header><p className="eyebrow">APP IDENTITY</p><h2>Branding</h2><p>These details appear on sign-in, navigation, browser metadata and the installed web app. The standard BB emblem is used until an administrator uploads a company logo.</p></header>{notice && <p className="form-success" role="status">{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}<form className="panel operations-form" onSubmit={save}><div className="branding-preview"><span style={{ backgroundImage: `url("${(logoDataUrl ?? branding.logoUrl).replaceAll('"', '%22')}")` }} /><div><strong>{branding.appName}</strong><small>{branding.companyName}</small></div></div><div className="operations-field-grid"><label>App name<input name="appName" required maxLength={60} defaultValue={branding.appName} key={`app-${branding.updatedAt}`} /></label><label>Installed short name<input name="shortName" required maxLength={24} defaultValue={branding.shortName} key={`short-${branding.updatedAt}`} /></label><label>Company name<input name="companyName" required maxLength={100} defaultValue={branding.companyName} key={`company-${branding.updatedAt}`} /></label><label>Subtitle<input name="subtitle" required maxLength={100} defaultValue={branding.subtitle} key={`subtitle-${branding.updatedAt}`} /></label><label className="span-2">Company logo <small>Optional square PNG, JPEG or WebP; maximum 750 KB. If omitted, the standard BB logo is shown.</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => chooseLogo(event.target.files?.[0])} /></label></div><div className="form-actions"><button className="primary" disabled={busy}>{busy ? "Saving…" : "Save branding"}</button><button type="button" className="secondary" disabled={busy} onClick={() => void restoreLogo()}>Use standard BB logo</button></div></form></section>;
}
