"use client";

import { FormEvent, type ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";

export type OperationsModule = "parades" | "duties" | "committees" | "leave" | "promotion" | "service" | "band" | "emergency";
type Row = Record<string, unknown>;
type Member = { id: number; name: string; rank: string; section: string; squad: string; band_member?: number };
type Event = { id: number; title: string; event_date: string; section: string };
type Permissions = { readOnly: boolean; finalAuthority: boolean; squadManager: boolean; canReviewLeaveSquad: boolean; canApproveLeave: boolean; canVerifyServiceSquad: boolean; canApproveService: boolean; canManagePlans: boolean; canManageDuties: boolean; canManageCommittees: boolean; canReviewLeave: boolean; canManagePromotion: boolean; canReviewService: boolean; canViewBand: boolean; canManageBand: boolean; canManageEmergency: boolean; canViewEmergencyContacts: boolean; ownMemberId: number | null };

const labels: Record<OperationsModule, { eyebrow: string; title: string; copy: string }> = {
  parades: { eyebrow: "PROGRAMME OPERATIONS", title: "Parade planner", copy: "Build reusable programmes, prepare squad drafts and publish a locked company plan." },
  duties: { eyebrow: "PROGRAMME OPERATIONS", title: "Duty roster", copy: "Assign duties, cover substitutions and spot unfilled responsibilities early." },
  committees: { eyebrow: "EVENT DELIVERY", title: "Event committees", copy: "Keep committee roles, tasks, deadlines and progress together." },
  leave: { eyebrow: "ATTENDANCE", title: "Leave requests", copy: "Request event leave and complete the squad and final review stages." },
  promotion: { eyebrow: "MEMBER PROGRESS", title: "Promotion readiness", copy: "Compare live attendance, awards, training and verified service against configured requirements." },
  service: { eyebrow: "MEMBER PROGRESS", title: "Service hours", copy: "Submit service, confirm it at squad level and complete Officer verification." },
  band: { eyebrow: "BAND OPERATIONS", title: "Band Centre", copy: "Manage band profiles, instruments, rehearsals, performances and proficiency." },
  emergency: { eyebrow: "SAFEGUARDING", title: "Emergency roll call", copy: "Record who is safe, missing, departed or still unknown without exposing contacts in notifications." },
};

function value(form: FormData, name: string) { return String(form.get(name) ?? "").trim(); }
function statusLabel(value: unknown) { return String(value ?? "unknown").replaceAll("_", " "); }
function dateLabel(value: unknown) { if (!value) return "No date"; const date = new Date(String(value)); return Number.isNaN(date.valueOf()) ? String(value) : date.toLocaleDateString("en-MY", { dateStyle: "medium" }); }

export default function CompanyOperationsCentre({ module, activeSection }: { module: OperationsModule; activeSection: "senior" | "junior" }) {
  const [data, setData] = useState<Record<string, unknown>>({}); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/company-operations?module=${module}`, { cache: "no-store" }); const result = await response.json() as Record<string, unknown> & { error?: string }; if (!response.ok) throw new Error(result.error ?? "Unable to load this workspace"); setData(result); }, [module]);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load this workspace")); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const permissions = (data.permissions ?? {}) as Partial<Permissions>; const members = useMemo(() => (data.members ?? []) as Member[], [data.members]); const events = (data.events ?? []) as Event[];
  const sectionMembers = useMemo(() => members.filter((member) => member.section === activeSection), [activeSection, members]);
  async function post(payload: Record<string, unknown>, success?: string) { setBusy(true); setError(""); setNotice(""); try { const response = await fetch("/api/company-operations", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(payload) }); const result = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(result.error ?? "The action could not be completed"); setNotice(result.message ?? success ?? "Action completed."); await load(); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "The action could not be completed"); return false; } finally { setBusy(false); } }
  async function submit(event: FormEvent<HTMLFormElement>, build: (form: FormData) => Record<string, unknown>) { event.preventDefault(); const formElement = event.currentTarget; const ok = await post(build(new FormData(formElement))); if (ok) formElement.reset(); }
  const memberOptions = <>{sectionMembers.map((member) => <option key={member.id} value={member.id}>{member.name} · {member.rank} · {member.squad}</option>)}</>;
  const eventOptions = <>{events.filter((event) => event.section === "all" || event.section === activeSection).map((event) => <option key={event.id} value={event.id}>{dateLabel(event.event_date)} · {event.title}</option>)}</>;
  const meta = labels[module];
  return <main className="operations-centre">
    <header className="category-page-header operations-header"><div><p className="eyebrow">{meta.eyebrow}</p><h1>{meta.title}</h1><p>{meta.copy}</p></div><span className="operations-scope">{activeSection === "senior" ? "Senior" : "Junior"} Section</span></header>
    {notice && <p className="form-success" role="status">{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}
    {module === "parades" && <Parades data={data} permissions={permissions} activeSection={activeSection} busy={busy} submit={submit} post={post} eventOptions={eventOptions} />}
    {module === "duties" && <Duties data={data} permissions={permissions} activeSection={activeSection} busy={busy} submit={submit} post={post} memberOptions={memberOptions} eventOptions={eventOptions} />}
    {module === "committees" && <Committees data={data} permissions={permissions} activeSection={activeSection} busy={busy} submit={submit} post={post} memberOptions={memberOptions} eventOptions={eventOptions} />}
    {module === "leave" && <Leave data={data} permissions={permissions} busy={busy} submit={submit} post={post} memberOptions={memberOptions} eventOptions={eventOptions} />}
    {module === "promotion" && <Promotion data={data} permissions={permissions} activeSection={activeSection} busy={busy} submit={submit} post={post} memberOptions={memberOptions} />}
    {module === "service" && <Service data={data} permissions={permissions} busy={busy} submit={submit} post={post} memberOptions={memberOptions} />}
    {module === "band" && <Band data={data} permissions={permissions} busy={busy} submit={submit} post={post} memberOptions={memberOptions} />}
    {module === "emergency" && <Emergency data={data} permissions={permissions} activeSection={activeSection} busy={busy} submit={submit} post={post} memberOptions={memberOptions} eventOptions={eventOptions} />}
  </main>;
}

type Shared = { data: Record<string, unknown>; permissions: Partial<Permissions>; busy: boolean; submit: (event: FormEvent<HTMLFormElement>, build: (form: FormData) => Record<string, unknown>) => Promise<void>; post: (payload: Record<string, unknown>, success?: string) => Promise<boolean>; memberOptions?: ReactNode; eventOptions?: ReactNode; activeSection?: "senior" | "junior" };
function Empty({ children }: { children: string }) { return <p className="operations-empty">{children}</p>; }
function Status({ value }: { value: unknown }) { return <span className={`operations-status status-${String(value ?? "unknown")}`}>{statusLabel(value)}</span>; }

function Parades({ data, permissions, activeSection, busy, submit, post, eventOptions }: Shared) { const templates=(data.templates??[]) as Row[]; const plans=(data.plans??[]) as Row[]; return <div className="operations-layout">
  {permissions.canManagePlans && <form className="panel operations-form" onSubmit={(event)=>submit(event,(form)=>({action:"create_parade_plan",title:value(form,"title"),planDate:value(form,"planDate"),eventId:value(form,"eventId"),section:activeSection,squad:value(form,"squad"),items:[{activity:value(form,"activity"),startsAt:value(form,"startsAt"),endsAt:value(form,"endsAt"),location:value(form,"location"),personInCharge:value(form,"personInCharge"),notes:value(form,"notes")}]}))}><div><p className="eyebrow">NEW DRAFT</p><h2>Plan a parade</h2></div><div className="operations-field-grid"><label>Plan title<input name="title" required placeholder="Weekly parade" /></label><label>Date<input name="planDate" type="date" required /></label><label>Linked meeting<select name="eventId"><option value="">Not linked</option>{eventOptions}</select></label><label>Squad<input name="squad" placeholder="Leave blank for company-wide" /></label><label>Start<input name="startsAt" type="time" /></label><label>End<input name="endsAt" type="time" /></label><label className="span-2">Activity<input name="activity" required placeholder="Opening parade" /></label><label>Location<input name="location" /></label><label>Person in charge<input name="personInCharge" /></label><label className="span-2">Notes<textarea name="notes" rows={3} /></label></div><button className="primary" disabled={busy}>{busy?"Saving…":"Save draft"}</button></form>}
  <section className="panel operations-list"><div className="operations-section-heading"><div><p className="eyebrow">PARADE PLANS</p><h2>Prepared plans</h2></div><span>{plans.length}</span></div>{plans.map((plan)=><article key={String(plan.id)}><div><strong>{String(plan.title)}</strong><small>{dateLabel(plan.plan_date)} · {String(plan.squad||"Company-wide")}</small></div><Status value={plan.status}/>{permissions.finalAuthority&&plan.status==="draft"&&<button className="secondary" disabled={busy} onClick={()=>void post({action:"publish_parade_plan",planId:plan.id,lock:true})}>Publish & lock</button>}</article>)}{!plans.length&&<Empty>No parade plans yet.</Empty>}</section>
  <section className="panel operations-list"><div className="operations-section-heading"><div><p className="eyebrow">REUSABLE</p><h2>Templates</h2></div><span>{templates.length}</span></div>{templates.map((item)=><article key={String(item.id)}><div><strong>{String(item.name)}</strong><small>{String(item.section)} · {String(item.squad||"Company-wide")}</small></div></article>)}{!templates.length&&<Empty>Create a plan first, then add reusable templates as needed.</Empty>}</section>
  {permissions.canManagePlans&&<form className="panel operations-form compact" onSubmit={(event)=>submit(event,(form)=>({action:"create_parade_template",name:value(form,"name"),section:activeSection,squad:value(form,"squad"),notes:value(form,"notes"),items:[{activity:value(form,"activity"),startsAt:value(form,"startsAt"),endsAt:value(form,"endsAt"),location:value(form,"location"),personInCharge:value(form,"personInCharge"),notes:value(form,"itemNotes")}]}))}><h2>New reusable template</h2><label>Template name<input name="name" required /></label><label>Squad<input name="squad" placeholder="Company-wide" /></label><label>Activity<input name="activity" required placeholder="Opening parade" /></label><div className="operations-field-grid"><label>Start<input name="startsAt" type="time" /></label><label>End<input name="endsAt" type="time" /></label><label>Location<input name="location" /></label><label>Person in charge<input name="personInCharge" /></label></div><label>Activity notes<input name="itemNotes" /></label><label>Template notes<textarea name="notes" rows={2}/></label><button className="primary" disabled={busy}>Create template</button></form>}
  </div>; }

function Duties({ data, permissions, activeSection, busy, submit, memberOptions, eventOptions }: Shared) { const dutyTypes=(data.dutyTypes??[]) as Row[]; const assignments=(data.assignments??[]) as Row[]; return <div className="operations-layout">
  {permissions.canManageDuties&&<form className="panel operations-form" onSubmit={(event)=>submit(event,(form)=>({action:"assign_duty",memberId:value(form,"memberId"),section:activeSection,squad:value(form,"squad"),dutyTypeId:value(form,"dutyTypeId"),dutyName:(form.get("dutyTypeId")&&dutyTypes.find((item)=>String(item.id)===value(form,"dutyTypeId"))?.name)||"Company duty",eventId:value(form,"eventId"),startsAt:value(form,"startsAt"),endsAt:value(form,"endsAt"),notes:value(form,"notes")}))}><div><p className="eyebrow">ASSIGNMENT</p><h2>Assign a duty</h2></div><div className="operations-field-grid"><label>Member<select name="memberId" defaultValue=""><option value="">Leave unfilled</option>{memberOptions}</select></label><label>Squad <small>Used for unfilled duties</small><input name="squad" placeholder="Company-wide"/></label><label>Duty type<select name="dutyTypeId" required defaultValue=""><option value="" disabled>Select duty</option>{dutyTypes.map((item)=><option value={String(item.id)} key={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Event<select name="eventId"><option value="">No linked event</option>{eventOptions}</select></label><label>Starts<input name="startsAt" type="datetime-local" required/></label><label>Ends<input name="endsAt" type="datetime-local"/></label><label>Notes<input name="notes"/></label></div><button className="primary" disabled={busy}>Save duty</button></form>}
  <section className="panel operations-list wide"><div className="operations-section-heading"><div><p className="eyebrow">ROSTER</p><h2>Duty assignments</h2></div><span>{assignments.length}</span></div>{assignments.map((item)=><article key={String(item.id)}><div><strong>{String(item.duty_name)} · {String(item.member_name||"Unfilled")}</strong><small>{dateLabel(item.starts_at)} · {String(item.squad||"Company")}{item.event_title?` · ${item.event_title}`:""}</small>{item.availability_note&&<small>Availability: {String(item.availability_note)}</small>}</div><Status value={item.status}/>{(permissions.canManageDuties||Number(item.member_id)===permissions.ownMemberId)&&<details><summary>Availability</summary><form onSubmit={(event)=>submit(event,(form)=>({action:"update_duty_availability",assignmentId:item.id,available:value(form,"available")==="yes",availabilityNote:value(form,"availabilityNote")}))}><select name="available"><option value="yes">Available</option><option value="no">Unavailable</option></select><input name="availabilityNote" placeholder="Optional note"/><button className="secondary" disabled={busy}>Update</button></form></details>}{permissions.canManageDuties&&<details><summary>Substitute</summary><form onSubmit={(event)=>submit(event,(form)=>({action:"substitute_duty",assignmentId:item.id,memberId:value(form,"memberId")}))}><select name="memberId" required defaultValue=""><option value="" disabled>Replacement member</option>{memberOptions}</select><button className="secondary" disabled={busy}>Save</button></form></details>}</article>)}{!assignments.length&&<Empty>No duties assigned.</Empty>}</section>
  {permissions.finalAuthority&&<form className="panel operations-form compact" onSubmit={(event)=>submit(event,(form)=>({action:"create_duty_type",name:value(form,"name"),description:value(form,"description")}))}><h2>Add duty type</h2><label>Name<input name="name" required placeholder="Flag bearer"/></label><label>Description<input name="description"/></label><button className="primary" disabled={busy}>Add duty type</button></form>}
  </div>; }

function Committees({ data, permissions, activeSection, busy, submit, post, memberOptions, eventOptions }: Shared) { const committees=(data.committees??[]) as Row[]; const tasks=(data.tasks??[]) as Row[]; return <div className="operations-layout">
  {permissions.canManageCommittees&&<form className="panel operations-form" onSubmit={(event)=>submit(event,(form)=>({action:"create_committee",name:value(form,"name"),eventId:value(form,"eventId"),section:activeSection,squad:value(form,"squad"),notes:value(form,"notes")}))}><div><p className="eyebrow">NEW COMMITTEE</p><h2>Create committee</h2></div><div className="operations-field-grid"><label>Name<input name="name" required/></label><label>Event<select name="eventId"><option value="">No linked event</option>{eventOptions}</select></label><label>Squad<input name="squad" placeholder="Company-wide"/></label><label>Notes<input name="notes"/></label></div><button className="primary" disabled={busy}>Create committee</button></form>}
  <section className="panel operations-list"><div className="operations-section-heading"><div><p className="eyebrow">COMMITTEES</p><h2>Active groups</h2></div><span>{committees.length}</span></div>{committees.map((item)=><article key={String(item.id)}><div><strong>{String(item.name)}</strong><small>{String(item.member_count??0)} members · {String(item.open_tasks??0)} open tasks</small></div><Status value={item.status}/></article>)}{!committees.length&&<Empty>No committees yet.</Empty>}</section>
  {permissions.canManageCommittees&&committees.length>0&&<form className="panel operations-form compact" onSubmit={(event)=>submit(event,(form)=>({action:"add_committee_task",committeeId:value(form,"committeeId"),title:value(form,"title"),memberId:value(form,"memberId"),deadline:value(form,"deadline"),notes:value(form,"notes")}))}><h2>Add committee task</h2><label>Committee<select name="committeeId" required>{committees.map((item)=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Task<input name="title" required/></label><label>Assigned member<select name="memberId"><option value="">Unassigned</option>{memberOptions}</select></label><label>Deadline<input name="deadline" type="date"/></label><button className="primary" disabled={busy}>Add task</button></form>}
  {permissions.canManageCommittees&&committees.length>0&&<form className="panel operations-form compact" onSubmit={(event)=>submit(event,(form)=>({action:"add_committee_member",committeeId:value(form,"committeeId"),memberId:value(form,"memberId"),role:value(form,"role")}))}><h2>Add committee member</h2><label>Committee<select name="committeeId" required>{committees.map((item)=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Member<select name="memberId" required defaultValue=""><option value="" disabled>Select member</option>{memberOptions}</select></label><label>Committee role<input name="role" required placeholder="Secretary"/></label><button className="primary" disabled={busy}>Add member</button></form>}
  <section className="panel operations-list wide"><div className="operations-section-heading"><div><p className="eyebrow">TASKS</p><h2>Committee work</h2></div><span>{tasks.length}</span></div>{tasks.map((item)=><article key={String(item.id)}><div><strong>{String(item.title)}</strong><small>{String(item.assigned_member_name||"Unassigned")} · {dateLabel(item.deadline)}</small></div><Status value={item.status}/>{item.status!=="completed"&&<button className="secondary" disabled={busy} onClick={()=>void post({action:"update_committee_task",taskId:item.id,status:"completed",notes:item.notes})}>Complete</button>}</article>)}{!tasks.length&&<Empty>No committee tasks yet.</Empty>}</section>
  </div>; }

function Leave({ data, permissions, busy, submit, post, memberOptions, eventOptions }: Shared) { const requests=(data.requests??[]) as Row[]; return <div className="operations-layout">
  {!permissions.readOnly&&<form className="panel operations-form" onSubmit={(event)=>submit(event,(form)=>({action:"submit_leave",memberId:value(form,"memberId"),eventId:value(form,"eventId"),reason:value(form,"reason"),attachmentDocumentId:value(form,"attachmentDocumentId")}))}><div><p className="eyebrow">REQUEST LEAVE</p><h2>Event absence</h2></div><label>Member<select name="memberId" required defaultValue=""><option value="" disabled>Select member</option>{memberOptions}</select></label><label>Event<select name="eventId" required defaultValue=""><option value="" disabled>Select event</option>{eventOptions}</select></label><label>Reason<textarea name="reason" required rows={4}/></label><label>Supporting document ID <small>Optional—use an existing private document reference</small><input name="attachmentDocumentId" inputMode="numeric" /></label><button className="primary" disabled={busy}>Submit leave request</button></form>}
  <section className="panel operations-list wide"><div className="operations-section-heading"><div><p className="eyebrow">REQUESTS</p><h2>Leave review queue</h2></div><span>{requests.length}</span></div>{requests.map((item)=><article key={String(item.id)}><div><strong>{String(item.member_name)} · {String(item.event_title)}</strong><small>{dateLabel(item.event_date)} · {String(item.reason)}</small>{item.reviewer_notes&&<small>Review note: {String(item.reviewer_notes)}</small>}</div><Status value={item.status}/><div className="operations-row-actions">{permissions.canReviewLeaveSquad&&item.status==="pending_squad"&&<><button className="secondary" disabled={busy} onClick={()=>void post({action:"review_leave_squad",requestId:item.id,decision:"confirmed"})}>Confirm</button><button className="danger-button" disabled={busy} onClick={()=>void post({action:"review_leave_squad",requestId:item.id,decision:"rejected"})}>Reject</button></>}{permissions.canApproveLeave&&item.status==="pending_final"&&<><button className="primary" disabled={busy} onClick={()=>void post({action:"review_leave_final",requestId:item.id,decision:"approved"})}>Approve</button><button className="danger-button" disabled={busy} onClick={()=>void post({action:"review_leave_final",requestId:item.id,decision:"rejected"})}>Reject</button></>}</div></article>)}{!requests.length&&<Empty>No leave requests.</Empty>}</section>
  </div>; }

function Promotion({ data, permissions, activeSection, busy, submit, post }: Shared) { const rules=(data.rules??[]) as Row[]; const readiness=(data.readiness??[]) as Row[]; return <div className="operations-layout">
  {permissions.canManagePromotion&&<form className="panel operations-form" onSubmit={(event)=>submit(event,(form)=>({action:"save_promotion_rule",section:activeSection,targetRank:value(form,"targetRank"),minimumAttendancePercent:Number(value(form,"attendance")),requiredAwards:value(form,"awards").split(",").map(v=>v.trim()).filter(Boolean),requiredTraining:value(form,"training").split(",").map(v=>v.trim()).filter(Boolean),minimumServiceHours:Number(value(form,"serviceHours")),officerAssessmentRequired:form.get("assessment")==="on"}))}><div><p className="eyebrow">REQUIREMENTS</p><h2>Configure target rank</h2></div><div className="operations-field-grid"><label>Target rank<input name="targetRank" required/></label><label>Minimum attendance %<input name="attendance" type="number" min="0" max="100" required defaultValue="75"/></label><label>Awards <small>Comma-separated</small><input name="awards"/></label><label>Training <small>Comma-separated</small><input name="training"/></label><label>Verified service hours<input name="serviceHours" type="number" min="0" step="0.5" defaultValue="0"/></label><label className="check-row"><input name="assessment" type="checkbox"/> Officer assessment required</label></div><button className="primary" disabled={busy}>Save requirements</button></form>}
  <section className="panel operations-list"><div className="operations-section-heading"><div><p className="eyebrow">RULES</p><h2>Configured ranks</h2></div><span>{rules.length}</span></div>{rules.filter((item)=>item.section===activeSection).map((item)=><article key={String(item.id)}><div><strong>{String(item.target_rank)}</strong><small>{String(item.minimum_attendance_percent)}% attendance · {String(item.minimum_service_hours)} service hours</small></div></article>)}{!rules.length&&<Empty>No promotion rules configured.</Empty>}</section>
  <section className="panel readiness-list wide"><div className="operations-section-heading"><div><p className="eyebrow">LIVE READINESS</p><h2>Member progress</h2></div><span>{readiness.length}</span></div>{readiness.filter((item)=>item.section===activeSection).map((item)=><article key={`${item.memberId}-${item.ruleId}`}><div className="readiness-title"><div><strong>{String(item.memberName)}</strong><small>Target: {String(item.targetRank)} · {String(item.squad)}</small></div><Status value={item.ready?"ready":"requirements_missing"}/></div><ul>{(item.checks as Array<{key:string;label:string;met:boolean;waived:boolean;value:string}>).map((check)=><li key={check.key} className={check.met||check.waived?"met":"missing"}><span>{check.met||check.waived?"✓":"○"}</span><div><strong>{check.label}</strong><small>{check.waived?"Waived":check.value}</small></div>{permissions.canManagePromotion&&!check.met&&!check.waived&&<button className="text-button" onClick={()=>{const reason=window.prompt("Reason for waiver");if(reason)void post({action:"waive_promotion_requirement",memberId:item.memberId,ruleId:item.ruleId,requirementKey:check.key,reason});}}>Waive</button>}</li>)}</ul>{permissions.canManagePromotion&&<button className="secondary" disabled={busy} onClick={()=>void post({action:"record_promotion_decision",memberId:item.memberId,ruleId:item.ruleId,decision:"approved",notes:"Readiness reviewed in app"})}>Record approval decision</button>}</article>)}{!readiness.length&&<Empty>Add promotion rules to calculate readiness.</Empty>}</section>
  </div>; }

function Service({ data, permissions, busy, submit, post, memberOptions }: Shared) { const submissions=(data.submissions??[]) as Row[]; return <div className="operations-layout">
  {!permissions.readOnly&&<form className="panel operations-form" onSubmit={(event)=>submit(event,(form)=>({action:"submit_service_hours",memberId:value(form,"memberId"),activity:value(form,"activity"),serviceDate:value(form,"serviceDate"),hours:Number(value(form,"hours")),minutes:Number(value(form,"minutes")),category:value(form,"category"),description:value(form,"description"),evidenceDocumentId:value(form,"evidenceDocumentId")}))}><div><p className="eyebrow">NEW RECORD</p><h2>Submit service hours</h2></div><div className="operations-field-grid"><label>Member<select name="memberId" required defaultValue=""><option value="" disabled>Select member</option>{memberOptions}</select></label><label>Date<input name="serviceDate" type="date" required/></label><label>Activity<input name="activity" required/></label><label>Category<select name="category"><option>Community</option><option>Church</option><option>Company</option><option>School</option><option>Other</option></select></label><label>Hours<input name="hours" type="number" min="0" max="24" defaultValue="1"/></label><label>Minutes<input name="minutes" type="number" min="0" max="59" defaultValue="0"/></label><label>Evidence document ID <small>Optional private document reference</small><input name="evidenceDocumentId" inputMode="numeric" /></label><label className="span-2">Description<textarea name="description" rows={3}/></label></div><button className="primary" disabled={busy}>Submit service hours</button></form>}
  <section className="panel operations-list wide"><div className="operations-section-heading"><div><p className="eyebrow">VERIFICATION</p><h2>Service records</h2></div><span>{submissions.length}</span></div>{submissions.map((item)=><article key={String(item.id)}><div><strong>{String(item.member_name)} · {String(item.activity)}</strong><small>{dateLabel(item.service_date)} · {(Number(item.duration_minutes)/60).toFixed(1)} hours · {String(item.category)}</small></div><Status value={item.status}/><div className="operations-row-actions">{permissions.canVerifyServiceSquad&&item.status==="pending_squad"&&<><button className="secondary" onClick={()=>void post({action:"review_service_squad",submissionId:item.id,decision:"confirmed"})}>Confirm</button><button className="danger-button" onClick={()=>void post({action:"review_service_squad",submissionId:item.id,decision:"rejected"})}>Reject</button></>}{permissions.canApproveService&&item.status==="pending_final"&&<><button className="primary" onClick={()=>void post({action:"review_service_final",submissionId:item.id,decision:"approved"})}>Approve</button><button className="danger-button" onClick={()=>void post({action:"review_service_final",submissionId:item.id,decision:"rejected"})}>Reject</button></>}</div></article>)}{!submissions.length&&<Empty>No service hours submitted.</Empty>}</section>
  </div>; }

function Band({ data, permissions, busy, submit, post, memberOptions }: Shared) { const profiles=(data.profiles??[]) as Row[]; const instruments=(data.instruments??[]) as Row[]; const rehearsals=(data.rehearsals??[]) as Row[]; const performances=(data.performances??[]) as Row[]; const assessments=(data.assessments??[]) as Row[]; return <div className="operations-layout">
  <section className="panel operations-callout wide"><div><p className="eyebrow">MUSIC LIBRARY</p><h2>Band resources</h2><p>Open approved music, rehearsal notes and band materials in the Resources library.</p></div><Link className="primary" href="/?open=resources">Open music resources</Link></section>
  {permissions.canManageBand&&<form className="panel operations-form" onSubmit={(event)=>submit(event,(form)=>({action:"save_band_profile",memberId:value(form,"memberId"),instrumentSection:value(form,"instrumentSection"),proficiency:value(form,"proficiency"),position:value(form,"position"),notes:value(form,"notes"),active:true}))}><div><p className="eyebrow">BAND PROFILE</p><h2>Add or update member</h2></div><div className="operations-field-grid"><label>Band member<select name="memberId" required defaultValue=""><option value="" disabled>Select member</option>{memberOptions}</select></label><label>Instrument section<input name="instrumentSection" required placeholder="Brass"/></label><label>Proficiency<select name="proficiency"><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Instructor</option></select></label><label>Position<input name="position" placeholder="Bandsman"/></label><label className="span-2">Notes<input name="notes"/></label></div><button className="primary" disabled={busy}>Save band profile</button></form>}
  <section className="panel operations-list"><div className="operations-section-heading"><div><p className="eyebrow">MEMBERS</p><h2>Band profiles</h2></div><span>{profiles.length}</span></div>{profiles.map((item)=><article key={String(item.member_id)}><div><strong>{String(item.name)}</strong><small>{String(item.instrument_section||"No section")} · {String(item.proficiency||"Not assessed")} · {String(item.position||"Member")}</small></div><Status value={item.active?"active":"inactive"}/></article>)}{!profiles.length&&<Empty>No band profiles yet.</Empty>}</section>
  {permissions.canManageBand&&<form className="panel operations-form compact" onSubmit={(event)=>submit(event,(form)=>({action:"add_band_instrument",name:value(form,"name"),instrumentSection:value(form,"instrumentSection"),serialNumber:value(form,"serialNumber"),condition:value(form,"condition"),maintenanceDueAt:value(form,"maintenanceDueAt"),notes:value(form,"notes")}))}><h2>Add instrument</h2><label>Name<input name="name" required/></label><label>Section<input name="instrumentSection" required/></label><label>Serial number<input name="serialNumber" required/></label><label>Condition<select name="condition"><option value="serviceable">Serviceable</option><option value="maintenance">Needs maintenance</option><option value="defective">Defective</option></select></label><label>Maintenance due<input name="maintenanceDueAt" type="date"/></label><button className="primary" disabled={busy}>Add instrument</button></form>}
  <section className="panel operations-list wide"><div className="operations-section-heading"><div><p className="eyebrow">INSTRUMENT REGISTER</p><h2>Company instruments</h2></div><span>{instruments.length}</span></div>{instruments.map((item)=><article key={String(item.id)}><div><strong>{String(item.name)} · {String(item.serial_number)}</strong><small>{String(item.instrument_section)} · {item.holder_name?`Held by ${item.holder_name}`:"Available"}{item.maintenance_due_at?` · Maintenance ${dateLabel(item.maintenance_due_at)}`:""}</small></div><Status value={item.condition}/>{permissions.canManageBand&&<div className="operations-row-actions">{!item.current_holder_member_id&&item.condition!=="defective"?<details><summary>Issue</summary><form onSubmit={(event)=>submit(event,(form)=>({action:"band_instrument_action",operation:"issue",instrumentId:item.id,memberId:value(form,"memberId"),dueAt:value(form,"dueAt")}))}><select name="memberId" required defaultValue=""><option value="" disabled>Member</option>{memberOptions}</select><input name="dueAt" type="date"/><button className="secondary">Issue</button></form></details>:item.current_holder_member_id?<button className="secondary" onClick={()=>void post({action:"band_instrument_action",operation:"return",instrumentId:item.id})}>Return</button>:null}</div>}</article>)}{!instruments.length&&<Empty>No instruments registered.</Empty>}</section>
  {permissions.canManageBand&&<div className="operations-mini-grid"><form className="panel operations-form compact" onSubmit={(event)=>submit(event,(form)=>({action:"add_band_rehearsal",title:value(form,"title"),date:value(form,"date"),location:value(form,"location"),notes:value(form,"notes")}))}><h2>Add rehearsal</h2><input name="title" required placeholder="Band rehearsal"/><input name="date" type="date" required/><input name="location" placeholder="Location"/><button className="primary">Add rehearsal</button></form><form className="panel operations-form compact" onSubmit={(event)=>submit(event,(form)=>({action:"add_band_performance",title:value(form,"title"),date:value(form,"date"),location:value(form,"location"),notes:value(form,"notes")}))}><h2>Add performance</h2><input name="title" required placeholder="Performance"/><input name="date" type="date" required/><input name="location" placeholder="Location"/><button className="primary">Add performance</button></form></div>}
  {permissions.canManageBand&&<form className="panel operations-form compact" onSubmit={(event)=>submit(event,(form)=>({action:"add_band_assessment",memberId:value(form,"memberId"),proficiency:value(form,"proficiency"),result:value(form,"result"),assessedAt:value(form,"assessedAt"),notes:value(form,"notes")}))}><h2>Record proficiency assessment</h2><label>Member<select name="memberId" required defaultValue=""><option value="" disabled>Select band member</option>{memberOptions}</select></label><label>Level<input name="proficiency" required/></label><label>Result<select name="result"><option>Passed</option><option>Developing</option><option>Not yet passed</option></select></label><label>Date<input name="assessedAt" type="date" required/></label><button className="primary" disabled={busy}>Save assessment</button></form>}
  {permissions.canManageBand&&rehearsals.length>0&&<form className="panel operations-form compact" onSubmit={(event)=>submit(event,(form)=>({action:"mark_band_rehearsal",rehearsalId:value(form,"rehearsalId"),memberId:value(form,"memberId"),status:value(form,"status")}))}><h2>Rehearsal attendance</h2><label>Rehearsal<select name="rehearsalId" required>{rehearsals.map((item)=><option key={String(item.id)} value={String(item.id)}>{dateLabel(item.rehearsal_date)} · {String(item.title)}</option>)}</select></label><label>Member<select name="memberId" required defaultValue=""><option value="" disabled>Select member</option>{memberOptions}</select></label><label>Status<select name="status"><option value="present">Present</option><option value="absent">Absent</option><option value="excused">Excused</option></select></label><button className="primary" disabled={busy}>Update attendance</button></form>}
  <section className="panel operations-summary wide"><article><strong>{rehearsals.length}</strong><span>Rehearsals</span></article><article><strong>{performances.length}</strong><span>Performances</span></article><article><strong>{assessments.length}</strong><span>Assessments</span></article></section>
  </div>; }

function Emergency({ data, permissions, activeSection, busy, submit, post, memberOptions, eventOptions }: Shared) { const sessions=(data.sessions??[]) as Row[]; const responses=(data.responses??[]) as Row[]; const active=sessions.find((item)=>item.status==="active"); const activeResponses=responses.filter((item)=>item.session_id===active?.id); return <div className="operations-layout">
  {permissions.canManageEmergency&&<form className="panel operations-form" onSubmit={(event)=>submit(event,(form)=>({action:"start_emergency",title:value(form,"title"),eventId:value(form,"eventId"),section:activeSection}))}><div><p className="eyebrow">NEW SESSION</p><h2>Start roll call</h2></div><label>Title<input name="title" required placeholder="Emergency roll call"/></label><label>Linked event<select name="eventId"><option value="">No linked event</option>{eventOptions}</select></label><p className="privacy-note">Emergency notifications contain no contact details. Every contact view and status change is audited.</p><button className="danger-button" disabled={busy}>Start emergency roll call</button></form>}
  <section className="panel operations-list"><div className="operations-section-heading"><div><p className="eyebrow">SESSIONS</p><h2>Roll-call history</h2></div><span>{sessions.length}</span></div>{sessions.map((item)=><article key={String(item.id)}><div><strong>{String(item.title)}</strong><small>{dateLabel(item.started_at)} · {String(item.section)}</small></div><Status value={item.status}/></article>)}{!sessions.length&&<Empty>No emergency sessions.</Empty>}</section>
  {active&&<section className="panel emergency-register wide"><div className="operations-section-heading"><div><p className="eyebrow">ACTIVE ROLL CALL</p><h2>{String(active.title)}</h2></div><div className="operations-row-actions"><span>{activeResponses.length}</span>{permissions.finalAuthority&&<button className="danger-button" disabled={busy} onClick={()=>void post({action:"close_emergency",sessionId:active.id})}>Close roll call</button>}</div></div><div className="emergency-counts">{["safe","missing","departed","unknown"].map((status)=><article key={status}><strong>{activeResponses.filter((item)=>item.status===status).length}</strong><span>{status}</span></article>)}</div>{activeResponses.map((item)=><article className="emergency-member" key={String(item.member_id)}><div><strong>{String(item.name)}</strong><small>{String(item.rank)} · {String(item.squad)}</small></div><Status value={item.status}/>{permissions.canManageEmergency&&<div className="segmented-actions">{["safe","missing","departed","unknown"].map((status)=><button key={status} className={item.status===status?"active":""} onClick={()=>void post({action:"update_emergency_response",sessionId:active.id,memberId:item.member_id,status})}>{status}</button>)}</div>}{permissions.canViewEmergencyContacts&&<button className="text-button" onClick={async()=>{const reason=window.prompt("Reason for viewing this emergency contact");if(!reason)return;const response=await fetch("/api/company-operations",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({action:"view_emergency_contact",memberId:item.member_id,reason})});const result=await response.json() as {contact?:{memberName:string;emergencyContactNumber:string;parentsName:string};error?:string};if(result.contact)window.alert(`${result.contact.memberName}\nEmergency: ${result.contact.emergencyContactNumber||"Not provided"}\nParent/guardian: ${result.contact.parentsName||"Not provided"}`);else window.alert(result.error||"Contact unavailable");}}>Emergency contact</button>}</article>)}</section>}
  {!active&&permissions.canManageEmergency&&<section className="panel operations-form compact"><h2>Quick member check</h2><select defaultValue=""><option value="" disabled>Select a member</option>{memberOptions}</select><p>Start a roll call to record live statuses.</p></section>}
  </div>; }
