"use client";

import { useCallback, useEffect, useState } from "react";

type Props = { user: { role: string; name: string }; currentYear: number };
type JsonRecord = Record<string, string | number | boolean | null | JsonRecord>;
type Data = { year: number; record: { id: number; status: string; captain_name: string; chaplain_name: string; submission_date: string; received_by: string; date_received: string; data_entry_name: string; remarks: string; notes: string } | null; inputs: JsonRecord; calculated: { memberCount: number; counts: Record<string, Record<string, { M: number; F: number; unknown: number }>>; ethnicity: Record<string, number>; spirituality: { acceptedChrist: number; baptised: number }; attendance: { sessions: number; marked: number }; missingClassification: Array<{ id: number; name: string }>; members: Array<{ id: number; name: string; gender: string; ethnicity: string }> }; validation: { warnings: string[]; canFinalize: boolean }; memberStatus: JsonRecord[] };
const empty: JsonRecord = { reEnrolled: {}, recruits: {}, primer: {}, associateMembers: {}, alumni: {}, officers: {}, ethnicity: {}, spirituality: {}, categoryMapping: {}, notes: "" };
const officerRanks = [
  ["ssgt", "Staff Sergeant"],
  ["warrantOfficer", "Warrant Officer"],
  ["lieutenant", "Lieutenant"],
  ["captain", "Captain"],
  ["honoraryCaptain", "Honorary Captain"],
  ["chaplain", "Chaplain"],
] as const;
const annualStatusFields = [
  ["workingM", "Working — Male (M)"],
  ["workingF", "Working — Female (F)"],
  ["studyingM", "Studying — Male (M)"],
  ["studyingF", "Studying — Female (F)"],
] as const;
const categories = ["Pre-Junior", "Junior", "Senior", "Primer"] as const;

function cell(value: unknown, onChange: (value: string) => void, disabled = false, label?: string) { return <input aria-label={label} className="stats-number" type="number" min="0" disabled={disabled} value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} />; }
function count(value: unknown) { const parsed = Number(value || 0); return Number.isFinite(parsed) ? parsed : 0; }
function escapeHtml(value: unknown) { return String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] || character); }

export default function CompanyStatisticsCentre({ user, currentYear }: Props) {
  const [year, setYear] = useState(currentYear); const [data, setData] = useState<Data | null>(null); const [inputs, setInputs] = useState<JsonRecord>(empty); const [fields, setFields] = useState<Record<string, string>>({}); const [newEthnicity, setNewEthnicity] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const readOnly = user.role === "viewer"; const locked = data?.record?.status === "final";
  const load = useCallback(async () => { setError(""); try { const response = await fetch(`/api/company-statistics?year=${year}`, { cache: "no-store" }); const result = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(result.error || "Unable to load statistics"); setData(result); const saved = { ...empty, ...(result.inputs || {}) }; const savedEthnicity = saved.ethnicity && typeof saved.ethnicity === "object" ? saved.ethnicity as JsonRecord : {}; const savedSpirituality = saved.spirituality && typeof saved.spirituality === "object" ? saved.spirituality as JsonRecord : {}; setInputs({ ...saved, ethnicity: Object.keys(savedEthnicity).length ? savedEthnicity : { ...result.calculated.ethnicity }, spirituality: Object.keys(savedSpirituality).length ? savedSpirituality : { acceptedChrist: result.calculated.spirituality.acceptedChrist, baptist: result.calculated.spirituality.baptised, nonBeliever: 0 } }); const record = result.record; setFields(record ? { captainName: record.captain_name, chaplainName: record.chaplain_name, submissionDate: record.submission_date, receivedBy: record.received_by, dateReceived: record.date_received, dataEntryName: record.data_entry_name, remarks: record.remarks, notes: record.notes } : {}); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load statistics"); } }, [year]);
  // The loader intentionally hydrates several independent UI states from one request.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const updateInput = (group: string, key: string, value: string) => setInputs((current) => ({ ...current, [group]: { ...(typeof current[group] === "object" && current[group] ? current[group] : {}), [key]: value } }));
  const removeInput = (group: string, key: string) => setInputs((current) => { const values = { ...(typeof current[group] === "object" && current[group] ? current[group] as JsonRecord : {}) }; delete values[key]; return { ...current, [group]: values }; });
  const addEthnicity = () => { const name = newEthnicity.trim(); if (!name) return; if (name.length > 60 || ["__proto__", "prototype", "constructor"].includes(name.toLowerCase())) { setError("Enter a valid ethnicity category of 60 characters or fewer."); return; } const values = inputs.ethnicity && typeof inputs.ethnicity === "object" ? inputs.ethnicity as JsonRecord : {}; if (Object.keys(values).some((key) => key.toLowerCase() === name.toLowerCase())) { setError("That ethnicity category already exists."); return; } updateInput("ethnicity", name, "0"); setNewEthnicity(""); setError(""); };
  const save = async (action: "save_draft" | "finalize" | "reopen") => { setBusy(true); setNotice(""); setError(""); try { const response = await fetch("/api/company-statistics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, year, inputs, fields }) }); const result = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(result.error || "Unable to save statistics"); setData(result); setNotice(action === "finalize" ? "Year finalised and locked." : action === "reopen" ? "Year reopened for correction." : "Draft saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save statistics"); } finally { setBusy(false); } };
  const exportExcel = async () => { if (!data) return; setBusy(true); try { const ExcelJS = await import("exceljs"); const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("Company Statistics"); sheet.addRow([`Company Statistics ${year}`]); sheet.addRow(["Membership category", "Male (M)", "Female (F)", "Unclassified", "Total"]); categories.forEach((key) => { const row = data.calculated.counts.continuing[key] || { M: 0, F: 0, unknown: 0 }; sheet.addRow([key, row.M, row.F, row.unknown, row.M + row.F + row.unknown]); }); sheet.addRow([]); sheet.addRow(["Officer rank", "Male (M)", "Female (F)", "Total"]); officerRanks.forEach(([key, label]) => { const values = inputs.officers as JsonRecord | undefined; const male = count(values?.[`${key}M`]); const female = count(values?.[`${key}F`]); sheet.addRow([label, male, female, male + female]); }); sheet.addRow([]); sheet.addRow(["Ethnicity", "Count"]); Object.entries(inputs.ethnicity as JsonRecord || {}).forEach(([key, value]) => sheet.addRow([key, count(value)])); sheet.addRow([]); sheet.addRow(["Spiritual status", "Count"]); const spirituality = inputs.spirituality as JsonRecord || {}; sheet.addRow(["Accepted Christ", count(spirituality.acceptedChrist)]); sheet.addRow(["Baptist", count(spirituality.baptist)]); sheet.addRow(["Non-Believer", count(spirituality.nonBeliever)]); sheet.addRow([]); sheet.addRow(["Metric", "Value"]); sheet.addRow(["Total members", data.calculated.memberCount]); sheet.addRow(["Attendance sessions counted", data.calculated.attendance.sessions]); sheet.addRow(["Attendance details marked", data.calculated.attendance.marked]); const inputSheet = workbook.addWorksheet("Supplemental Inputs"); inputSheet.addRow(["Group", "Field", "Value"]); Object.entries(inputs).forEach(([group, values]) => { if (values && typeof values === "object") Object.entries(values as Record<string, unknown>).forEach(([key, value]) => { const annualLabel = ["associateMembers", "alumni"].includes(group) ? annualStatusFields.find(([field]) => field === key)?.[1] : undefined; inputSheet.addRow([group, annualLabel || key, value]); }); }); const validation = workbook.addWorksheet("Validation"); validation.addRow(["Warnings"]); data.validation.warnings.forEach((warning) => validation.addRow([warning])); const buffer = await workbook.xlsx.writeBuffer(); const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `company-statistics-${year}.xlsx`; link.click(); URL.revokeObjectURL(link.href); await fetch("/api/company-statistics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "export", year, format: "excel" }) }); setNotice("Excel workbook downloaded."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to export Excel"); } finally { setBusy(false); } };
  const print = () => { if (!data) return; const popup = window.open("", "company-statistics-print", "width=1000,height=800"); if (!popup) { setError("Allow pop-ups to print the report."); return; } const ethnicity = inputs.ethnicity as JsonRecord || {}; const spirituality = inputs.spirituality as JsonRecord || {}; popup.document.write(`<html><head><title>Company Statistics ${year}</title><style>body{font:11px Arial;color:#111}h1{font-size:18px;text-align:center}table{border-collapse:collapse;width:100%;margin:8px 0}td,th{border:1px solid #333;padding:4px}th{background:#eee}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media print{ @page{size:A4 portrait;margin:12mm}}</style></head><body><h1>Company Statistics ${year}</h1><p>Company: 11th Kuching</p><table><tr><th>Membership summary</th><th>Count</th></tr><tr><td>Total members</td><td>${data.calculated.memberCount}</td></tr><tr><td>Attendance sessions counted</td><td>${data.calculated.attendance.sessions}</td></tr><tr><td>Attendance details marked</td><td>${data.calculated.attendance.marked}</td></tr></table><div class="grid"><table><tr><th>Ethnicity</th><th>Count</th></tr>${Object.entries(ethnicity).map(([key,value])=>`<tr><td>${escapeHtml(key)}</td><td>${count(value)}</td></tr>`).join("")}</table><table><tr><th>Spiritual status</th><th>Count</th></tr><tr><td>Accepted Christ</td><td>${count(spirituality.acceptedChrist)}</td></tr><tr><td>Baptist</td><td>${count(spirituality.baptist)}</td></tr><tr><td>Non-Believer</td><td>${count(spirituality.nonBeliever)}</td></tr></table></div><h3>Supplemental annual details</h3><pre>${escapeHtml(JSON.stringify(inputs,null,2))}</pre><p>Captain: ${escapeHtml(fields.captainName)} &nbsp; Chaplain: ${escapeHtml(fields.chaplainName)}</p></body></html>`); popup.document.close(); popup.focus(); popup.print(); void fetch("/api/company-statistics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "export", year, format: "print" }) }); };
  if (!data) return <main className="category-page"><div className="loading-state">Preparing company statistics…</div></main>;
  return <main className="category-page company-statistics-page"><header className="category-page-header"><div><p className="eyebrow">ADMINISTRATION</p><h1>Company Statistics</h1><p>Annual snapshot, validation and print-ready reporting.</p></div><label className="stats-year">Reporting year<select value={year} onChange={(event) => setYear(Number(event.target.value))}>{Array.from({ length: 5 }, (_, index) => currentYear - index).map((value) => <option key={value}>{value}</option>)}</select></label></header>
    <section className="stats-status panel"><div><strong>{locked ? "Finalised and locked" : "Draft"}</strong><span>{data.calculated.memberCount} members · {data.validation.warnings.length ? `${data.validation.warnings.length} warning(s)` : "Ready for review"}</span></div><div className="stats-actions">{!readOnly && !locked && <><button type="button" className="secondary-button" disabled={busy} onClick={() => void save("save_draft")}>Save draft</button><button type="button" className="primary-button" disabled={busy || !data.validation.canFinalize} onClick={() => void save("finalize")}>Finalise year</button></>}{locked && user.role === "admin" && <button type="button" className="secondary-button" disabled={busy} onClick={() => void save("reopen")}>Reopen year</button>}<button type="button" className="secondary-button" disabled={busy} onClick={print}>Export PDF</button><button type="button" className="secondary-button" disabled={busy} onClick={() => void exportExcel()}>Export Excel</button></div></section>
    {notice && <p className="form-success" role="status">✓ {notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}{data.validation.warnings.length > 0 && <section className="stats-warning panel"><strong>Before finalising</strong><ul>{data.validation.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></section>}
    <section className="stats-preview panel"><div className="panel-heading"><div><p className="eyebrow">CALCULATED FROM APP DATA</p><h2>Membership table</h2></div><span>{data.calculated.memberCount} total</span></div><div className="stats-table-wrap"><table className="stats-table"><thead><tr><th>Category</th><th>Male (M)</th><th>Female (F)</th><th>Unclassified</th><th>Total</th></tr></thead><tbody>{categories.map((key) => { const row = data.calculated.counts.continuing[key] || { M: 0, F: 0, unknown: 0 }; return <tr key={key}><td>{key}</td><td>{row.M}</td><td>{row.F}</td><td>{row.unknown}</td><td>{row.M + row.F + row.unknown}</td></tr>; })}</tbody></table></div><div className="stats-summary-strip"><strong>Total membership: {data.calculated.memberCount}</strong><span>Attendance counted: {data.calculated.attendance.sessions} sessions · {data.calculated.attendance.marked} details marked</span></div></section>
    <section className="stats-grid"><section className="panel"><p className="eyebrow">OFFICER TABLE</p><h2>Officer ranks</h2><div className="stats-table-wrap"><table className="stats-table stats-officer-table"><thead><tr><th>Rank</th><th>Male (M)</th><th>Female (F)</th><th>Total</th></tr></thead><tbody>{officerRanks.map(([key, label]) => { const values = inputs.officers as JsonRecord | undefined; const maleKey = `${key}M`; const femaleKey = `${key}F`; const male = count(values?.[maleKey]); const female = count(values?.[femaleKey]); return <tr key={key}><td>{label}</td><td>{cell(values?.[maleKey], (value) => updateInput("officers", maleKey, value), readOnly || locked, `${label} male`)}</td><td>{cell(values?.[femaleKey], (value) => updateInput("officers", femaleKey, value), readOnly || locked, `${label} female`)}</td><td>{male + female}</td></tr>; })}</tbody></table></div></section><section className="panel"><p className="eyebrow">ETHNICITY & SPIRITUAL STATUS</p><h2>Annual classifications</h2><h3 className="stats-subheading">Spiritual status</h3><div className="stats-input-group stats-single-column">{[["acceptedChrist","Accepted Christ"],["baptist","Baptist"],["nonBeliever","Non-Believer"]].map(([key,label]) => <label key={key}>{label}{cell((inputs.spirituality as JsonRecord | undefined)?.[key], (value) => updateInput("spirituality", key, value), readOnly || locked, label)}</label>)}</div><h3 className="stats-subheading">Ethnicity</h3><div className="stats-custom-list">{Object.entries(inputs.ethnicity as JsonRecord || {}).map(([key,value]) => <div className="stats-custom-row" key={key}><span>{key}</span>{cell(value, (next) => updateInput("ethnicity", key, next), readOnly || locked, `${key} count`)}{!readOnly && !locked && <button type="button" className="text-button danger" onClick={() => removeInput("ethnicity", key)}>Remove</button>}</div>)}</div>{!readOnly && !locked && <div className="stats-add-row"><input value={newEthnicity} onChange={(event) => setNewEthnicity(event.target.value)} placeholder="New ethnicity category" aria-label="New ethnicity category" /><button type="button" className="secondary-button" onClick={addEthnicity}>Add ethnicity</button></div>}</section></section>
    <section className="stats-grid"><section className="panel"><p className="eyebrow">ANNUAL SUPPLEMENTAL DETAILS</p><h2>Membership changes</h2>{data.calculated.missingClassification.length > 0 && <label className="stats-review-check"><input type="checkbox" disabled={readOnly || locked} checked={inputs.classificationComplete === true} onChange={(event) => setInputs({ ...inputs, classificationComplete: event.target.checked })} /> I have reviewed unclassified member fields for this annual snapshot.</label>}{[["reEnrolled","Re-enrolled"],["recruits","Recruits"],["primer","Primer"]].map(([group,label]) => <div className="stats-input-group" key={group}><strong>{label}</strong>{categories.map((key) => <label key={key}>{key}{cell((inputs[group] as JsonRecord | undefined)?.[key], (value) => updateInput(group,key,value), readOnly || locked, `${label} ${key}`)}</label>)}</div>)}</section><section className="panel"><p className="eyebrow">OFFICERS & OTHER</p><h2>Annual details</h2>{[["associateMembers","Associate members"],["alumni","Alumni"]].map(([group,label]) => <div className="stats-input-group" key={group}><strong>{label}</strong>{annualStatusFields.map(([key, fieldLabel]) => <label key={key}>{fieldLabel}{cell((inputs[group] as JsonRecord | undefined)?.[key], (value) => updateInput(group,key,value), readOnly || locked, `${label} ${fieldLabel}`)}</label>)}</div>)}</section></section>
    <section className="stats-grid"><section className="panel"><p className="eyebrow">DECLARATION</p><h2>Signatories</h2>{[["captainName","Captain’s name"],["chaplainName","Chaplain’s name"],["submissionDate","Submission date"],["notes","Annual notes"]].map(([key,label]) => <label className="field" key={key}>{label}{key === "notes" ? <textarea disabled={readOnly || locked} value={fields[key] || ""} onChange={(event) => setFields({ ...fields, [key]: event.target.value })} /> : <input disabled={readOnly || locked} value={fields[key] || ""} onChange={(event) => setFields({ ...fields, [key]: event.target.value })} />}</label>)}</section><section className="panel"><p className="eyebrow">OFFICER USE</p><h2>Review details</h2>{[["receivedBy","Received by"],["dateReceived","Date received"],["dataEntryName","Data-entry name"],["remarks","Remarks"]].map(([key,label]) => <label className="field" key={key}>{label}<input disabled={readOnly || locked} value={fields[key] || ""} onChange={(event) => setFields({ ...fields, [key]: event.target.value })} /></label>)}</section></section>
  </main>;
}
