"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type EventItem = { id: number; title: string; event_date: string; end_date: string | null; location: string; description: string; section: string; attendance_session_id: number | null; rsvp_total: number; going_total: number };
type Rsvp = { event_id: number; status: string; note: string };

export default function EventCentre() {
  const [events, setEvents] = useState<EventItem[]>([]); const [rsvps, setRsvps] = useState<Rsvp[]>([]);
  const [canManage, setCanManage] = useState(false); const [readOnly, setReadOnly] = useState(false);
  const [formOpen, setFormOpen] = useState(false); const [busy, setBusy] = useState<number | string | null>(null); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/events", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load events"); setEvents(result.events ?? []); setRsvps(result.rsvps ?? []); setCanManage(Boolean(result.canManage)); setReadOnly(Boolean(result.readOnly)); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load events")); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function post(body: Record<string, unknown>) { setError(""); const response = await fetch("/api/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to update events"); setNotice(result.message ?? "Saved."); await load(); }
  async function rsvp(eventId: number, status: string) { setBusy(eventId); try { await post({ action: "rsvp", eventId, status }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save RSVP"); } finally { setBusy(null); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy("create"); try { await post({ action: "create", title: data.get("title"), eventDate: data.get("eventDate"), endDate: data.get("endDate"), section: data.get("section"), location: data.get("location"), description: data.get("description"), createAttendance: data.get("attendance") === "on" }); setFormOpen(false); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create event"); } finally { setBusy(null); } }
  return <main className="event-centre-page">
    <header className="category-page-header"><div><p className="eyebrow">PROGRAMME & EVENTS</p><h1>Meetings and events</h1><p>Keep the company programme, RSVPs and attendance follow-up in one place.</p></div>{canManage && <button className="primary" onClick={() => setFormOpen((value) => !value)}>{formOpen ? "Close" : "+ Add event"}</button>}</header>
    {notice && <p className="form-success" role="status">{notice}</p>}{error && <p className="form-error">{error}</p>}
    {formOpen && <form className="event-form panel" onSubmit={create}><div className="panel-heading"><h2>Plan an event</h2><span>Members will receive an in-app notification.</span></div><div className="event-form-grid"><label>Title<input name="title" required maxLength={120} placeholder="e.g. Weekly Parade" /></label><label>Date and time<input name="eventDate" type="datetime-local" required /></label><label>Section<select name="section" defaultValue="all"><option value="all">All sections</option><option value="senior">Senior</option><option value="junior">Junior</option></select></label><label>Location<input name="location" maxLength={160} placeholder="Optional location" /></label><label className="event-wide">Details<textarea name="description" rows={3} maxLength={2000} placeholder="What members need to know" /></label><label className="event-check"><input name="attendance" type="checkbox" defaultChecked /> Create an attendance register for this event</label></div><button className="primary" disabled={busy === "create"}>{busy === "create" ? "Creating…" : "Create event"}</button></form>}
    <section className="event-timeline" aria-live="polite">{events.map((event) => { const response = rsvps.find((item) => item.event_id === event.id)?.status ?? ""; const date = new Date(event.event_date); return <article className="event-card panel" key={event.id}><time dateTime={event.event_date}><strong>{date.toLocaleDateString("en-MY", { day: "2-digit" })}</strong><span>{date.toLocaleDateString("en-MY", { month: "short" })}</span></time><div className="event-body"><p className="eyebrow">{event.section === "all" ? "COMPANY EVENT" : `${event.section.toUpperCase()} SECTION`}</p><h2>{event.title}</h2><p>{date.toLocaleString("en-MY", { dateStyle: "medium", timeStyle: "short" })}{event.location ? ` · ${event.location}` : ""}</p>{event.description && <small>{event.description}</small>}<span className="event-attendance">{event.attendance_session_id ? "Attendance register ready" : "No attendance register"}{canManage ? ` · ${event.going_total ?? 0} going` : ""}</span></div>{!readOnly && <div className="rsvp-actions"><small>Your RSVP</small>{[["going", "Going"], ["maybe", "Maybe"], ["not_going", "Can’t go"]].map(([status, label]) => <button key={status} disabled={busy === event.id} className={response === status ? "active" : ""} onClick={() => rsvp(event.id, status)}>{label}</button>)}</div>}</article>; })}{!events.length && <div className="event-empty panel"><span>◫</span><h2>No upcoming events</h2><p>New meetings and company events will appear here.</p></div>}</section>
  </main>;
}
