"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type EventItem = { id: number; title: string; event_date: string; end_date: string | null; location: string; description: string; section: string; audience: string; attendance_session_id: number | null; attendance_required: number; attendance_marked: number; rsvp_total: number; going_total: number };
type Rsvp = { event_id: number; status: string; note: string };

export default function EventCentre() {
  const [events, setEvents] = useState<EventItem[]>([]); const [rsvps, setRsvps] = useState<Rsvp[]>([]);
  const [serverNow, setServerNow] = useState("");
  const [canManage, setCanManage] = useState(false); const [readOnly, setReadOnly] = useState(false);
  const [formOpen, setFormOpen] = useState(false); const [busy, setBusy] = useState<number | string | null>(null); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/events", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load events"); setEvents(result.events ?? []); setRsvps(result.rsvps ?? []); setServerNow(String(result.now ?? "")); setCanManage(Boolean(result.canManage)); setReadOnly(Boolean(result.readOnly)); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load events")); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function post(body: Record<string, unknown>) { setError(""); const response = await fetch("/api/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to update events"); setNotice(result.message ?? "Saved."); await load(); }
  async function rsvp(eventId: number, status: string) { setBusy(eventId); try { await post({ action: "rsvp", eventId, status }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save RSVP"); } finally { setBusy(null); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy("create"); try { await post({ action: "create", title: data.get("title"), eventDate: data.get("eventDate"), endDate: data.get("endDate"), section: data.get("section"), audience: data.get("audience"), location: data.get("location"), description: data.get("description"), createAttendance: data.get("attendance") === "on" }); setFormOpen(false); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create event"); } finally { setBusy(null); } }
  return <main className="event-centre-page">
    <header className="category-page-header"><div><p className="eyebrow">PROGRAMME & EVENTS</p><h1>Meetings and events</h1><p>Keep the company programme, RSVPs and attendance follow-up in one place.</p></div>{canManage && <button className="primary" onClick={() => setFormOpen((value) => !value)}>{formOpen ? "Close" : "+ Add event"}</button>}</header>
    {notice && <p className="form-success" role="status">{notice}</p>}{error && <p className="form-error">{error}</p>}
    {formOpen && <form className="event-form panel" onSubmit={create}><div className="panel-heading"><div><p className="eyebrow">NEW PROGRAMME ITEM</p><h2>Plan an event</h2></div><span>Only the selected attendees will be notified.</span><button className="event-form-close" type="button" onClick={() => setFormOpen(false)} aria-label="Close event planner">×</button></div><div className="event-form-grid"><label>Title<input name="title" required maxLength={120} placeholder="e.g. NCO Council Meeting" /></label><label>Date and time<input name="eventDate" type="datetime-local" required /></label><label>Section<select name="section" defaultValue="senior"><option value="all">All sections</option><option value="senior">Senior</option><option value="junior">Junior</option></select></label><label>Required attendees<select name="audience" defaultValue="section_members"><option value="section_members">All members in this section</option><option value="nco_council">NCO Council — NCOs and Squad Leaders only</option></select><small>NCO Council meetings are always kept within the Senior Section.</small></label><label className="event-wide">Location<input name="location" maxLength={160} placeholder="Optional location" /></label><label className="event-wide">Details<textarea name="description" rows={3} maxLength={2000} placeholder="What the selected attendees need to know" /></label><label className="event-register-toggle"><input name="attendance" type="checkbox" defaultChecked /><span><strong>Create an attendance register</strong><small>Only required attendees will appear in the register.</small></span></label></div><button className="primary" disabled={busy === "create"}>{busy === "create" ? "Creating…" : "Create event"}</button></form>}
    <div className="event-attendance-legend" aria-label="Attendance colour guide"><span className="complete">● Attendance updated</span><span className="pending">● Attendance to update</span><span className="scheduled">● Upcoming meeting</span><span className="none">● No register</span></div>
    <section className="event-timeline" aria-live="polite">{events.map((event) => { const response = rsvps.find((item) => item.event_id === event.id)?.status ?? ""; const date = new Date(event.event_date); const isUpcoming = Boolean(serverNow) && date.getTime() > new Date(serverNow).getTime(); const required = Number(event.attendance_required ?? 0); const marked = Number(event.attendance_marked ?? 0); const attendanceState = !event.attendance_session_id ? "none" : isUpcoming ? "scheduled" : required > 0 && marked >= required ? "complete" : "pending"; const attendanceLabel = !event.attendance_session_id ? "No attendance register" : isUpcoming ? "Attendance opens after the meeting" : required === 0 ? "No attendees require marking" : attendanceState === "complete" ? `Attendance updated · ${marked}/${required} marked` : `Attendance to update · ${marked}/${required} marked`; const audienceLabel = event.audience === "nco_council" ? "NCO COUNCIL" : event.section === "all" ? "COMPANY EVENT" : `${event.section.toUpperCase()} SECTION`; return <article className={`event-card panel attendance-${attendanceState}`} key={event.id}><time dateTime={event.event_date}><strong>{date.toLocaleDateString("en-MY", { day: "2-digit" })}</strong><span>{date.toLocaleDateString("en-MY", { month: "short" })}</span></time><div className="event-body"><p className="eyebrow">{audienceLabel}</p><h2>{event.title}</h2><p>{date.toLocaleString("en-MY", { dateStyle: "medium", timeStyle: "short" })}{event.location ? ` · ${event.location}` : ""}</p>{event.description && <small>{event.description}</small>}<span className={`event-attendance ${attendanceState}`}>{attendanceLabel}{canManage ? ` · ${event.going_total ?? 0} going` : ""}</span></div>{!readOnly && <div className="rsvp-actions"><small>Your RSVP</small>{[["going", "Going"], ["maybe", "Maybe"], ["not_going", "Can’t go"]].map(([status, label]) => <button key={status} disabled={busy === event.id} className={response === status ? "active" : ""} onClick={() => rsvp(event.id, status)}>{label}</button>)}</div>}</article>; })}{!events.length && <div className="event-empty panel"><span>◫</span><h2>No upcoming events</h2><p>New meetings and company events will appear here.</p></div>}</section>
  </main>;
}
