"use client";
import { FormEvent, useEffect, useState } from "react";
import type { ShellUser } from "./AppShell";
type Analytics = { attendance?: Array<{ section: string; registers: number; present: number; recorded: number }>; stock?: Array<{ stock_type: string; low_stock: number }>; attendanceTrend?: Array<{ month: string; present: number; recorded: number }>; retention?: Array<{ joined_year: string; total: number; retained: number }>; squadComparison?: Array<{ section: string; squad: string; members: number; average_service_years: number }> };
type Message = { id: number; subject: string; body: string; created_at: string };
type Recipient = { id: number; name: string; role: string; squad: string };
type Template = { id: number; name: string; description: string };
function parseCsv(value: string) { const lines = value.split(/\r?\n/).filter((line) => line.trim()); if (!lines.length) return [] as Array<Record<string, string>>; const split = (line: string) => line.split(",").map((cell) => cell.trim().replace(/^"|"$/g, "")); const headers = split(lines[0]); return lines.slice(1).map((line) => Object.fromEntries(split(line).map((cell, index) => [headers[index] ?? `column_${index + 1}`, cell]))); }
export default function ExpansionCentre({ user }: { user: ShellUser }) {
  const [tab, setTab] = useState<"analytics" | "messages" | "import" | "templates" | "public">("analytics"); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [recipients, setRecipients] = useState<Recipient[]>([]); const [templates, setTemplates] = useState<Template[]>([]); const [jobId, setJobId] = useState<number | null>(null); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const isAdmin = user.role === "admin" || user.temporary_access_role === "temporary_admin"; const canMessage = !["member", "viewer"].includes(user.role);
  useEffect(() => { if (tab !== "analytics") return; fetch("/api/feature-expansion?kind=analytics", { cache: "no-store" }).then(async (r) => { const x = await r.json() as Analytics; if (r.ok) setAnalytics(x); }).catch(() => undefined); }, [tab]);
  useEffect(() => { if (tab !== "messages") return; Promise.all([fetch("/api/feature-expansion?kind=messages", { cache: "no-store" }), fetch("/api/feature-expansion?kind=recipients", { cache: "no-store" })]).then(async ([a, b]) => { const x = await a.json() as { messages?: Message[] }; const y = await b.json() as { recipients?: Recipient[] }; if (a.ok) setMessages(x.messages ?? []); if (b.ok) setRecipients(y.recipients ?? []); }).catch(() => undefined); }, [tab]);
  useEffect(() => { if (tab !== "templates") return; fetch("/api/feature-expansion?kind=report-templates", { cache: "no-store" }).then(async (r) => { const x = await r.json() as { templates?: Template[] }; if (r.ok) setTemplates(x.templates ?? []); }).catch(() => undefined); }, [tab]);
  async function post(body: Record<string, unknown>) { setBusy(true); setError(""); try { const r = await fetch("/api/feature-expansion", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const x = await r.json() as { error?: string; message?: string; jobId?: number }; if (!r.ok) throw new Error(x.error ?? "Unable to complete action"); setNotice(x.message ?? "Saved."); return x; } finally { setBusy(false); } }
  async function previewImport(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const file = f.get("file"); let rows: unknown[] = []; try { if (file instanceof File && file.size) { if (file.name.toLowerCase().endsWith(".xlsx")) { const ExcelJS = await import("exceljs"); const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(await file.arrayBuffer()); const sheet = workbook.worksheets[0]; const values = sheet.getRow(1).values as unknown[]; const headers = values.slice(1).map((value) => String(value ?? "").trim()); sheet.eachRow((row, index) => { if (index === 1) return; const cells = row.values as unknown[]; rows.push(Object.fromEntries(headers.map((header, i) => [header, String(cells[i + 1] ?? "")] ))); }); } else rows = parseCsv(await file.text()); } else rows = JSON.parse(String(f.get("rows") ?? "[]")) as unknown[]; const x = await post({ action: "preview_import", fileName: file instanceof File && file.name ? file.name : f.get("fileName"), rows }); setJobId(x.jobId ?? null); } catch (e) { setError(e instanceof Error ? e.message : "Choose a valid Excel, CSV, or JSON file."); } }
  async function importAction(action: "commit_import" | "rollback_import") { if (!jobId) return; try { await post({ action, jobId }); if (action === "rollback_import") setJobId(null); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update import"); } }
  async function saveTemplate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); try { await post({ action: "save_report_template", name: f.get("name"), description: f.get("description"), datasets: f.getAll("datasets") }); event.currentTarget.reset(); setTab("templates"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save template"); } }
  return <section className="panel expansion-centre"><div className="panel-heading"><div><p className="eyebrow">OPERATIONS TOOLS</p><h2>Insights and communication</h2><p>Import, reporting, analytics and public updates.</p></div></div><div className="admin-tabs" role="tablist" aria-label="Expansion tools">{([["analytics", "Analytics"], ["messages", "Messages"], ["import", "Excel import"], ["templates", "Report templates"], ["public", "Public information"]] as const).map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={tab === value} className={tab === value ? "active" : ""} onClick={() => { setTab(value); setNotice(""); setError(""); }}>{label}</button>)}</div>{notice && <p className="form-success" role="status">{notice}</p>}{error && <p className="form-error">{error}</p>}
    {tab === "analytics" && <div className="expansion-grid"><div className="home-snapshot expansion-stats">{(analytics?.attendance ?? []).map((r) => <article className="panel" key={`a-${r.section}`}><span>{r.section} attendance</span><strong>{r.recorded ? Math.round(Number(r.present) / Number(r.recorded) * 100) : 0}%</strong><small>{r.registers} registers</small></article>)}{(analytics?.stock ?? []).map((r) => <article className="panel" key={`s-${r.stock_type}`}><span>{r.stock_type} stock</span><strong>{r.low_stock}</strong><small>low-stock items</small></article>)}</div><article className="panel"><h3>Attendance trend</h3>{(analytics?.attendanceTrend ?? []).map((r) => <p key={r.month}><strong>{r.month}</strong> · {r.present}/{r.recorded} recorded</p>)}{!analytics?.attendanceTrend?.length && <p className="analytics-empty">No attendance trend data yet.</p>}</article><article className="panel"><h3>Retention by joining year</h3>{(analytics?.retention ?? []).map((r) => <p key={r.joined_year}><strong>{r.joined_year}</strong> · {r.retained}/{r.total} retained</p>)}{!analytics?.retention?.length && <p className="analytics-empty">No retention data yet.</p>}</article><article className="panel"><h3>Squad comparison</h3>{(analytics?.squadComparison ?? []).map((r) => <p key={`${r.section}-${r.squad}`}><strong>{r.squad}</strong> · {r.members} members · {r.average_service_years} years average</p>)}{!analytics?.squadComparison?.length && <p className="analytics-empty">No squad data yet.</p>}</article></div>}
    {tab === "messages" && <div className="expansion-grid"><div className="audit-list">{messages.map((m) => <article key={m.id}><div><strong>{m.subject}</strong><small>{m.body}</small></div><time>{new Date(m.created_at).toLocaleString("en-MY")}</time></article>)}{!messages.length && <p className="empty-state">No messages yet.</p>}</div>{canMessage && <form className="panel inline-form" onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); try { await post({ action: "send_message", recipientUserId: Number(f.get("recipientUserId")), subject: f.get("subject"), message: f.get("message") }); e.currentTarget.reset(); } catch (x) { setError(x instanceof Error ? x.message : "Unable to send message"); } }}><h3>Start a message thread</h3><select name="recipientUserId" required defaultValue=""><option value="" disabled>Select recipient</option>{recipients.map((r) => <option key={r.id} value={r.id}>{r.name} · {r.role}{r.squad ? ` · ${r.squad}` : ""}</option>)}</select><input name="subject" placeholder="Subject" /><textarea name="message" required rows={4} placeholder="Message" /><button className="primary" disabled={busy}>{busy ? "Sending…" : "Send message"}</button></form>}</div>}
    {tab === "import" && <div className="expansion-grid"><form className="panel stacked-form import-form" onSubmit={previewImport}><h3>Import members</h3><p>Upload Excel or CSV, preview validation, then commit. Excel files use the first worksheet.</p><input name="file" type="file" accept=".xlsx,.xls,.csv,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" /><input name="fileName" defaultValue="member-import.xlsx" /><textarea name="rows" rows={6} placeholder={'Or paste JSON: [{"name":"Example","email":"member@example.com","section":"senior","squad":"Alpha"}]'} /><button className="primary" disabled={busy}>{busy ? "Checking…" : "Preview import"}</button></form>{jobId && <article className="panel"><h3>Import preview ready</h3><p>Job #{jobId} validated. Commit creates members; rollback removes only records from this commit.</p><button type="button" className="primary" onClick={() => void importAction("commit_import")} disabled={busy}>Commit import</button>{isAdmin && <button type="button" className="danger-button" onClick={() => void importAction("rollback_import")} disabled={busy}>Rollback import</button>}</article>}</div>}
    {tab === "templates" && <div className="expansion-grid"><form className="panel stacked-form template-form" onSubmit={saveTemplate}><h3>Create report template</h3><input name="name" required placeholder="Template name" /><input name="description" placeholder="Description" /><fieldset><legend>Datasets</legend>{["members", "attendance", "awards", "submissions", "subscriptions", "stock"].map((dataset) => <label key={dataset}><input type="checkbox" name="datasets" value={dataset} /> {dataset}</label>)}</fieldset><button className="primary" disabled={busy}>Save template</button></form><div className="audit-list">{templates.map((t) => <article key={t.id}><div><strong>{t.name}</strong><small>{t.description || "No description"}</small></div>{isAdmin && <button type="button" className="danger-button" onClick={() => void post({ action: "delete_report_template", templateId: t.id })}>Delete</button>}</article>)}{!templates.length && <p className="empty-state">No report templates yet.</p>}</div></div>}
    {tab === "public" && <div className="expansion-grid expansion-grid-single">{isAdmin ? <form className="panel stacked-form" onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); try { await post({ action: "publish", title: f.get("title"), body: f.get("body"), contentType: "notice" }); e.currentTarget.reset(); } catch (x) { setError(x instanceof Error ? x.message : "Unable to publish"); } }}><h3>Publish public information</h3><p className="form-help">Share a notice or resource with the public information page.</p><label>Title<input name="title" required placeholder="e.g. Registration information" /></label><label>Message<textarea name="body" required rows={6} placeholder="Public notice or resource information" /></label><button className="primary" disabled={busy}>{busy ? "Publishing…" : "Publish"}</button></form> : <p className="empty-state">Only administrators can publish public information.</p>}</div>}
  </section>;
}
