"use client";

import { FormEvent, useEffect, useState } from "react";
import type { ShellUser } from "./AppShell";

type Analytics = { attendance?: Array<{ section: string; registers: number; present: number; recorded: number }>; awards?: Array<{ section: string; status: string; total: number }>; subscriptions?: Array<{ section: string; paid: number; total: number }>; stock?: Array<{ stock_type: string; items: number; low_stock: number }> };
type Message = { id: number; subject: string; body: string; sender_user_id: number; recipient_user_id: number; read_at: string | null; created_at: string };

function parseCsv(value: string) {
  const lines = value.split(/\r?\n/).filter((line) => line.trim());
  if (!lines.length) return [] as Array<Record<string, string>>;
  const split = (line: string) => line.split(",").map((cell) => cell.trim().replace(/^"|"$/g, ""));
  const headers = split(lines[0]);
  return lines.slice(1).map((line) => Object.fromEntries(split(line).map((cell, index) => [headers[index] ?? `column_${index + 1}`, cell])));
}

export default function ExpansionCentre({ user }: { user: ShellUser }) {
  const [tab, setTab] = useState<"analytics" | "messages" | "import" | "public">("analytics");
  const [analytics, setAnalytics] = useState<Analytics | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const isAdmin = user.role === "admin" || user.temporary_access_role === "temporary_admin";
  const canMessage = !["member", "viewer"].includes(user.role);
  useEffect(() => { if (tab !== "analytics") return; fetch("/api/feature-expansion?kind=analytics", { cache: "no-store" }).then(async (response) => { const result = await response.json() as Analytics; if (response.ok) setAnalytics(result); }).catch(() => undefined); }, [tab]);
  useEffect(() => { if (tab !== "messages") return; fetch("/api/feature-expansion?kind=messages", { cache: "no-store" }).then(async (response) => { const result = await response.json() as { messages?: Message[] }; if (response.ok) setMessages(result.messages ?? []); }).catch(() => undefined); }, [tab]);
  async function post(body: Record<string, unknown>) { setBusy(true); setError(""); const response = await fetch("/api/feature-expansion", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string; message?: string; summary?: unknown }; setBusy(false); if (!response.ok) throw new Error(result.error ?? "Unable to complete action"); setNotice(result.message ?? "Saved."); return result; }
  async function sendMessage(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await post({ action: "send_message", recipientUserId: Number(form.get("recipientUserId")), subject: form.get("subject"), message: form.get("message") }); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to send message"); } }
  async function previewImport(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); let rows: unknown[] = []; const file = form.get("file"); try { if (file instanceof File && file.size) rows = parseCsv(await file.text()); else rows = JSON.parse(String(form.get("rows") ?? "[]")) as unknown[]; } catch { setError("Choose a CSV file or paste a valid JSON array."); return; } try { const result = await post({ action: "preview_import", fileName: file instanceof File && file.name ? file.name : form.get("fileName"), rows }); setNotice(`Preview created: ${JSON.stringify(result.summary)}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to preview import"); } }
  async function publish(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await post({ action: "publish", title: form.get("title"), body: form.get("body"), contentType: "notice" }); event.currentTarget.reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to publish"); } }
  return <section className="panel expansion-centre"><div className="panel-heading"><div><p className="eyebrow">NEW OPERATIONS TOOLS</p><h2>Insights and communication</h2><p>Use these optional tools without changing existing records.</p></div></div><div className="admin-tabs" role="tablist" aria-label="Expansion tools">{([["analytics", "Analytics"], ["messages", "Messages"], ["import", "Import preview"], ["public", "Public information"]] as const).map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={tab === value} className={tab === value ? "active" : ""} onClick={() => { setTab(value); setNotice(""); setError(""); }}>{label}</button>)}</div>{notice && <p className="form-success" role="status">{notice}</p>}{error && <p className="form-error">{error}</p>}
    {tab === "analytics" && <div className="home-snapshot expansion-stats">{(analytics?.attendance ?? []).map((row) => <article className="panel" key={`attendance-${row.section}`}><span>{row.section} attendance</span><strong>{row.recorded ? Math.round((Number(row.present) / Number(row.recorded)) * 100) : 0}%</strong><small>{row.registers} registers</small></article>)}{(analytics?.stock ?? []).map((row) => <article className="panel" key={`stock-${row.stock_type}`}><span>{row.stock_type} stock</span><strong>{row.low_stock}</strong><small>low-stock items</small></article>)}{(analytics?.awards ?? []).map((row) => <article className="panel" key={`award-${row.section}-${row.status}`}><span>{row.section} awards</span><strong>{row.total}</strong><small>{row.status.replaceAll("_", " ")}</small></article>)}{(analytics?.subscriptions ?? []).map((row) => <article className="panel" key={`subscription-${row.section}-${row.paid}`}><span>{row.section} subscriptions</span><strong>{row.total}</strong><small>{Number(row.paid) ? "paid" : "unpaid"}</small></article>)}</div>}
    {tab === "messages" && <div className="expansion-grid"><div className="audit-list">{messages.map((message) => <article key={message.id}><div><strong>{message.subject}</strong><small>{message.body}</small></div><time>{new Date(message.created_at).toLocaleString("en-MY")}</time></article>)}{!messages.length && <p className="empty-state">No messages yet.</p>}</div>{canMessage && <form className="panel inline-form" onSubmit={sendMessage}><h3>Send a staff message</h3><input name="recipientUserId" type="number" required placeholder="Recipient account ID" /><input name="subject" placeholder="Subject" /><textarea name="message" required rows={4} placeholder="Message" /><button className="primary" disabled={busy}>{busy ? "Sending…" : "Send message"}</button></form>}</div>}
    {tab === "import" && <form className="panel stacked-form" onSubmit={previewImport}><h3>Preview member import</h3><p>Choose a CSV exported from Excel, or paste a JSON array. This step validates only; it does not change member records.</p><input name="file" type="file" accept=".csv,text/csv" /><input name="fileName" defaultValue="member-import.json" /><textarea name="rows" rows={8} placeholder={'[{"name":"Example Member","email":"member@example.com"}]'} /><button className="primary" disabled={busy}>{busy ? "Checking…" : "Preview import"}</button></form>}
    {tab === "public" && (isAdmin ? <form className="panel stacked-form" onSubmit={publish}><h3>Publish public information</h3><p>Only this selected content is visible without signing in.</p><input name="title" required placeholder="Title" /><textarea name="body" required rows={6} placeholder="Public notice or resource information" /><button className="primary" disabled={busy}>{busy ? "Publishing…" : "Publish"}</button></form> : <p className="empty-state">Only administrators can publish public information.</p>)}
  </section>;
}
