"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Member={id:number;name:string;rank:string;section:string;email:string};
type Officer={id:number;name:string;officer_rank:string};
type Application={id:number;member_id:number;member_name:string;rank:string;section:string;status:string;application_year:number;exco_meeting_date?:string;awards_officer_user_id?:number;captain_user_id?:number;project_completed?:number;include_company_stamp?:number;notes?:string};
type Eligibility={eligible:boolean;age:number|null;checks:{label:string;met:boolean}[];awards:{award_code:string;award_name:string;awarded_at:string}[];attendanceYears:{year:number;percentage:number;present:number;counted:number}[]};
type ListData={applications:Application[];members:Member[];template?:{form_code:string};settings?:{company_number:string;official_company_name:string;malaysian_state:string};profile:{sha256:string;formCode:string};r2Available:boolean;permissions:{canManage:boolean;canTemplate:boolean;canOutcome:boolean}};
type DetailData={application:Application;member:Member&{nric:string;birth_date:string;passport_photo_object_key:string};versions:{id:number;version_number:number;created_at:string;superseded_at?:string}[];outcomes:{id:number;outcome:string;outcome_date:string;reference:string}[];officers:Officer[];eligibility:Eligibility;permissions:ListData["permissions"]};
const labels:Record<string,string>={requested:"Needs Officer",preparing:"Preparing",ready:"Ready",finalised:"Finalised",submitted:"Submitted",returned:"Returned",approved:"Approved",rejected:"Rejected",cancelled:"Cancelled"};

async function post(body:Record<string,unknown>){const response=await fetch("/api/junior-gold",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to complete request");return data;}

export default function JuniorGoldCentre({activeSection}:{activeSection:"senior"|"junior"}){
  const [list,setList]=useState<ListData|null>(null),[detail,setDetail]=useState<DetailData|null>(null),[selected,setSelected]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [draft,setDraft]=useState({nric:"",birthDate:"",excoMeetingDate:"",awardsOfficerId:"",captainId:"",notes:""});
  const loadList=useCallback(async()=>{const response=await fetch("/api/junior-gold",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setList(data);},[]);
  const loadDetail=useCallback(async(id:number)=>{const response=await fetch(`/api/junior-gold?applicationId=${id}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setDetail(data);setSelected(id);setDraft({nric:data.member.nric??"",birthDate:data.member.birth_date??"",excoMeetingDate:data.application.exco_meeting_date??"",awardsOfficerId:data.application.awards_officer_user_id?String(data.application.awards_officer_user_id):"",captainId:data.application.captain_user_id?String(data.application.captain_user_id):"",notes:data.application.notes??""});},[]);
  useEffect(()=>{const id=Number(new URL(window.location.href).searchParams.get("application"));const timer=window.setTimeout(()=>{loadList().then(()=>id&&loadDetail(id)).catch(cause=>setError(cause instanceof Error?cause.message:"Unable to load Junior Gold Award"));},0);return()=>window.clearTimeout(timer);},[loadDetail,loadList]);
  async function run(body:Record<string,unknown>,message:string){setBusy(true);setError("");try{const result=await post(body);setNotice(message);await loadList();if(selected)await loadDetail(selected);return result;}catch(cause){setError(cause instanceof Error?cause.message:"Unable to complete request");}finally{setBusy(false);}}
  async function upload(event:FormEvent<HTMLFormElement>,action:string,message:string){event.preventDefault();const formElement=event.currentTarget;setBusy(true);setError("");const form=new FormData(formElement);form.set("action",action);try{const response=await fetch("/api/junior-gold",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);setNotice(message);formElement.reset();await loadList();if(selected)await loadDetail(selected);}catch(cause){setError(cause instanceof Error?cause.message:"Upload failed");}finally{setBusy(false);}}
  function closeDetail(){setDetail(null);setSelected(null);const url=new URL(window.location.href);url.searchParams.delete("application");window.history.replaceState({},"",url);}
  if(!list)return <main className="presidents-badge-page"><p>Preparing Junior Gold Award applications…</p>{error&&<p className="error-banner">{error}</p>}</main>;
  if(detail&&selected)return <main className="presidents-badge-page">
    <div className="button-row"><button className="secondary" onClick={closeDetail}>← All applications</button>{!['finalised','submitted','approved'].includes(detail.application.status)&&<button className="danger-button" disabled={busy} onClick={()=>{if(window.confirm("Delete this Junior Gold Award application?"))void run({action:"delete_application",applicationId:selected},"Application deleted.").then(closeDetail);}}>Delete application</button>}</div>
    <header className="presidents-hero"><div><p className="eyebrow">JUNIOR GOLD AWARD APPLICATION</p><h1>{detail.member.name}</h1><p>{detail.member.rank} · {detail.member.section[0].toUpperCase()+detail.member.section.slice(1)} Section</p></div><span className={`status-chip status-${detail.application.status}`}>{labels[detail.application.status]??detail.application.status}</span></header>
    {error&&<p className="error-banner">{error}</p>}{notice&&<p className="success-banner">{notice}</p>}
    <div className="presidents-grid">
      <section className="presidents-card presidents-card-wide live-preview-card"><div className="card-heading"><div><p className="eyebrow">LIVE PREVIEW</p><h2>Official form data</h2></div><span className="status-chip">Page 1 of 2</span></div><div className="official-preview"><div className="preview-brand">JUNIOR GOLD AWARD <span>{detail.application.application_year}</span></div><div className="preview-grid"><div><small>Candidate</small><strong>{detail.member.name}</strong></div><div><small>Section / rank</small><strong>{detail.member.section} · {detail.member.rank}</strong></div><div><small>Birth date</small><strong>{draft.birthDate||"—"}</strong></div><div><small>Age on 1 January</small><strong>{detail.eligibility.age??"—"}</strong></div></div><div className="preview-awards"><div className="preview-awards-title">Preliminary awards and awarded years</div><div className="preview-award-list">{detail.eligibility.awards.map(award=><div key={award.award_code}><span>{award.award_name}</span><time>{award.awarded_at?.slice(0,4)||"Date missing"}</time></div>)}</div></div></div></section>
      <section className="presidents-card"><h2>Eligibility</h2><p className={detail.eligibility.eligible?"complete-text":"warning-text"}>{detail.eligibility.eligible?"All linked requirements are met.":"Complete the missing linked requirements before finalising."}</p><ul className="eligibility-list">{detail.eligibility.checks.map(check=><li key={check.label} className={check.met?"met":"missing"}><span>{check.met?"✓":"!"}</span>{check.label}</li>)}</ul></section>
      <section className="presidents-card"><h2>Junior attendance</h2>{detail.eligibility.attendanceYears.length?<ul>{detail.eligibility.attendanceYears.map(row=><li key={row.year}>{row.year}: {row.percentage}% ({row.present}/{row.counted})</li>)}</ul>:<p>No completed Junior attendance sessions found.</p>}</section>
      <section className="presidents-card"><h2>Candidate details</h2><form onSubmit={event=>{event.preventDefault();void run({action:"save_member_details",applicationId:selected,nric:draft.nric,birthDate:draft.birthDate},"Candidate details saved.");}}><label>NRIC<input value={draft.nric} onChange={event=>setDraft({...draft,nric:event.target.value})} required/></label><label>Birth date<input type="date" value={draft.birthDate} onChange={event=>setDraft({...draft,birthDate:event.target.value})} required/></label><button className="primary" disabled={busy}>Save details</button></form><form onSubmit={event=>upload(event,"upload_photo","Passport photo saved.")}><input type="hidden" name="memberId" value={detail.member.id}/><label>Passport photo<input type="file" name="file" accept="image/png,image/jpeg" required/></label><button className="secondary" disabled={busy}>Upload photo</button></form></section>
      {detail.permissions.canManage&&<section className="presidents-card presidents-card-wide"><h2>Prepare application</h2><form className="form-grid" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run({action:"save",applicationId:selected,excoMeetingDate:draft.excoMeetingDate,awardsOfficerId:draft.awardsOfficerId,captainId:draft.captainId,projectCompleted:form.get("projectCompleted")==="on",includeCompanyStamp:form.get("includeCompanyStamp")==="on",notes:draft.notes},"Application saved.");}}><label>EXCO meeting date<input type="date" value={draft.excoMeetingDate} onChange={event=>setDraft({...draft,excoMeetingDate:event.target.value})}/></label><label>Awards Officer<select value={draft.awardsOfficerId} onChange={event=>setDraft({...draft,awardsOfficerId:event.target.value})}><option value="">Select Officer</option>{detail.officers.map(officer=><option key={officer.id} value={officer.id}>{officer.name} — {officer.officer_rank||"Officer"}</option>)}</select></label><label>Captain<select value={draft.captainId} onChange={event=>setDraft({...draft,captainId:event.target.value})}><option value="">Select Captain</option>{detail.officers.map(officer=><option key={officer.id} value={officer.id}>{officer.name} — {officer.officer_rank||"Officer"}</option>)}</select></label><label className="check-row"><input type="checkbox" name="projectCompleted" defaultChecked={Boolean(detail.application.project_completed)}/>BBM HQ assignment / project / test completed</label><label className="check-row"><input type="checkbox" name="includeCompanyStamp" defaultChecked={Boolean(detail.application.include_company_stamp)}/>Place the saved company stamp</label><label className="span-all">Notes<textarea rows={3} value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})}/></label><button className="primary" disabled={busy}>Save preparation</button></form><form onSubmit={event=>upload(event,"upload_signature","Your signature was saved privately.")}><label>My reusable signature<input type="file" name="file" accept="image/png,image/jpeg" required/></label><button className="secondary" disabled={busy}>Save signature</button></form></section>}
      <section className="presidents-card"><h2>Finalised PDF versions</h2>{detail.versions.length?<ul>{detail.versions.map(version=><li key={version.id}>Version {version.version_number} · <a href={`/api/junior-gold/download?applicationId=${selected}&versionId=${version.id}`}>Download</a>{version.superseded_at&&" · superseded"}</li>)}</ul>:<p>No locked version yet.</p>}{detail.permissions.canManage&&<div className="button-row">{!['finalised','submitted','approved'].includes(detail.application.status)&&<button className="primary" disabled={busy} onClick={()=>void run({action:"finalise",applicationId:selected},"A locked two-page PDF was created.")}>Validate and finalise</button>}{detail.application.status==='finalised'&&<><button className="secondary" onClick={()=>void run({action:"reopen",applicationId:selected},"Application reopened.")}>Reopen</button><button className="primary" onClick={()=>void run({action:"mark_submitted",applicationId:selected},"External submission recorded.")}>Mark submitted</button></>}</div>}</section>
      {detail.permissions.canOutcome&&<section className="presidents-card"><h2>External BBM outcome</h2><p>Only confirmed BBM approval awards Gold Award in the member record.</p><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run({action:"record_outcome",applicationId:selected,outcome:form.get("outcome"),outcomeDate:form.get("outcomeDate"),reference:form.get("reference"),confirmed:form.get("confirmed")==="on"},"Outcome recorded.");}}><label>Outcome<select name="outcome" required><option value="">Choose</option><option value="returned">Returned</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><label>Decision date<input type="date" name="outcomeDate" required/></label><label>BBM reference<input name="reference"/></label><label className="check-row"><input type="checkbox" name="confirmed"/>Confirmed external BBM decision</label><button className="primary" disabled={busy}>Record outcome</button></form></section>}
    </div>
  </main>;
  const visibleMembers=list.members.filter(member=>member.section===activeSection);
  return <main className="presidents-badge-page"><header className="presidents-hero"><div><p className="eyebrow">PEOPLE → AWARDS</p><h1>Junior Gold Award Applications</h1><p>Prepare the official two-page AWA-JR01/2010-9 form. Junior alumni who have moved to Senior remain eligible and visible.</p></div></header>{error&&<p className="error-banner">{error}</p>}{notice&&<p className="success-banner">{notice}</p>}{!list.r2Available&&<p className="warning-banner">Private R2 storage is not connected. Exact templates and final PDFs require the DOCUMENTS binding.</p>}<div className="presidents-grid">
    <section className="presidents-card"><h2>Start an application</h2><form onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const result=await run({action:"create",memberId:form.get("memberId")},"Application created.");if(result?.applicationId)void loadDetail(result.applicationId);}}><label>Junior or Senior member<select name="memberId" required><option value="">Choose member</option>{visibleMembers.map(member=><option key={member.id} value={member.id}>{member.name} — {member.section} · {member.rank}</option>)}</select></label><button className="primary" disabled={busy}>Start application</button></form></section>
    {list.permissions.canTemplate&&<section className="presidents-card"><h2>Exact official template</h2><p>{list.template?`${list.template.form_code} verified and stored privately.`:"Upload the supplied exact official PDF."}</p><code className="hash-code">{list.profile.sha256}</code><form onSubmit={event=>upload(event,"upload_template","Official template verified and stored privately.")}><label>Official PDF<input type="file" name="file" accept="application/pdf" required/></label><button className="secondary" disabled={busy}>Verify and upload</button></form></section>}
    {list.permissions.canManage&&<section className="presidents-card"><h2>Official company details</h2><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run({action:"save_settings",companyNumber:form.get("companyNumber"),companyName:form.get("companyName"),state:form.get("state")},"Company details saved.");}}><label>BB company number<input name="companyNumber" defaultValue={list.settings?.company_number??""}/></label><label>Official company name<input name="companyName" defaultValue={list.settings?.official_company_name??""}/></label><label>Malaysian state<input name="state" defaultValue={list.settings?.malaysian_state??""}/></label><button className="secondary">Save company details</button></form>{list.permissions.canTemplate&&<form onSubmit={event=>upload(event,"upload_stamp","Company stamp saved privately.")}><label>Optional company stamp<input type="file" name="file" accept="image/png,image/jpeg" required/></label><button className="secondary" disabled={busy}>Upload stamp</button></form>}</section>}
    {list.permissions.canManage&&<section className="presidents-card"><h2>Annual compliance dates</h2><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run({action:"save_compliance",year:form.get("year"),brigadeDuesDate:form.get("brigadeDuesDate"),rosReturnDate:form.get("rosReturnDate"),statisticsReturnDate:form.get("statisticsReturnDate")},"Compliance dates saved.");}}><label>Reporting year<input type="number" name="year" defaultValue={new Date().getFullYear()} min="2000" max="2100"/></label><label>Brigade Dues paid<input type="date" name="brigadeDuesDate"/></label><label>ROS Return submitted<input type="date" name="rosReturnDate"/></label><label>Statistics Return submitted<input type="date" name="statisticsReturnDate"/></label><button className="secondary">Save dates</button></form></section>}
    <section className="presidents-card presidents-card-wide"><h2>Applications</h2>{list.applications.length?<div className="application-list">{list.applications.map(application=><button key={application.id} onClick={()=>void loadDetail(application.id)}><span><strong>{application.member_name}</strong><small>{application.section} · {application.rank} · {application.application_year}</small></span><span className={`status-chip status-${application.status}`}>{labels[application.status]??application.status}</span></button>)}</div>:<div className="empty-state"><h3>No applications yet</h3><p>Eligible members in either Junior or Senior Section can begin here.</p></div>}</section>
  </div></main>;
}
