"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Application = { id:number;member_id:number;member_name:string;rank:string;status:string;application_year:number;exco_meeting_date:string;owner_user_id:number|null;updated_at:string };
type Member = { id:number;name:string;rank:string;squad:string;section:string;email:string;school?:string;nric?:string;birth_date?:string;passport_photo_object_key?:string };
type Officer = { id:number;name:string;email:string;officer_rank:string;contact_number:string };
type Assessment = { id:number;assessor_type:string;completion_mode:string;assessor_name:string;status:string;submitted_at:string|null };
type Award = { award_code:string; award_name:string; level:string; awarded_at:string; category:string };
type Version = { id:number;version_number:number;sha256:string;created_at:string;superseded_at:string|null };
type Permission = { canManage:boolean;canTemplate:boolean;canEndorse:boolean;canOutcome:boolean };
type ListData = { applications:Application[];members:Member[];template?:{form_code:string;sha256:string;created_at:string};settings?:Record<string,string>;profile:{formCode:string;sha256:string;fileSize:number};r2Available:boolean;permissions:Permission };
type DetailData = { application:Application & { awards_officer_user_id:number|null;captain_user_id:number|null;include_company_stamp:number;notes:string };member:Member;assessments:Assessment[];versions:Version[];camps:Array<{id:number;camp_year:number;camp_level:string;description:string}>;outcomes:Array<{id:number;outcome:string;outcome_date:string;reference:string;returned_document_object_key:string}>;officers:Officer[];eligibility:{checks:Array<{label:string;met:boolean}>;eligible:boolean;awards:Award[]};permissions:Permission;r2Available:boolean };

const statusLabels: Record<string,string> = { requested:"Officer ownership needed",preparing:"Preparing",assessments_pending:"Assessments pending",captain_review:"Captain review",ready:"Ready to finalise",finalised:"Finalised",submitted:"Submitted to BBM",returned:"Returned",approved:"Approved by BBM",rejected:"Rejected by BBM",cancelled:"Cancelled" };

async function api(body: Record<string,unknown>) {
  const res = await fetch("/api/presidents-badge", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body) });
  const data = await res.json(); if (!res.ok) throw new Error(data.error ?? "Unable to complete request"); return data;
}

export default function PresidentsBadgeCentre() {
  const [list,setList]=useState<ListData|null>(null); const [detail,setDetail]=useState<DetailData|null>(null); const [selected,setSelected]=useState<number|null>(null); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false); const [invite,setInvite]=useState("");
  const [draft,setDraft]=useState({nric:"",birthDate:"",excoMeetingDate:"",awardsOfficerId:"",captainId:"",notes:""});
  const loadList=useCallback(async()=>{const res=await fetch("/api/presidents-badge",{cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error);setList(data);},[]);
  const loadDetail=useCallback(async(id:number)=>{const res=await fetch(`/api/presidents-badge?applicationId=${id}`,{cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error);setDetail(data);setDraft({nric:data.member?.nric??"",birthDate:data.member?.birth_date??"",excoMeetingDate:data.application?.exco_meeting_date??"",awardsOfficerId:data.application?.awards_officer_user_id?String(data.application.awards_officer_user_id):"",captainId:data.application?.captain_user_id?String(data.application.captain_user_id):"",notes:data.application?.notes??""});setSelected(id);const url=new URL(window.location.href);url.searchParams.set("application",String(id));window.history.replaceState({},"",url);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{loadList().then(()=>{const id=Number(new URL(window.location.href).searchParams.get("application"));if(id)void loadDetail(id);}).catch(c=>setError(c.message));},0);return()=>window.clearTimeout(timer);},[loadDetail,loadList]);
  async function run(body:Record<string,unknown>,message:string){setBusy(true);setError("");setNotice("");try{const data=await api(body);setNotice(message);await loadList();if(selected)await loadDetail(selected);return data;}catch(c){setError(c instanceof Error?c.message:"Unable to complete request");}finally{setBusy(false);}}
  async function deleteApplication() { if (!selected || !window.confirm("Delete this President’s Badge application?")) return; setBusy(true); setError(""); try { await api({action:"delete_application",applicationId:selected}); setDetail(null); setSelected(null); const u=new URL(window.location.href); u.searchParams.delete("application"); window.history.replaceState({},"",u); await loadList(); } catch (c) { setError(c instanceof Error?c.message:"Unable to delete application"); } finally { setBusy(false); } }
  async function upload(event:FormEvent<HTMLFormElement>,action:string,message:string){event.preventDefault();const formElement=event.currentTarget;setBusy(true);setError("");const form=new FormData(formElement);form.set("action",action);try{const res=await fetch("/api/presidents-badge",{method:"POST",body:form});const data=await res.json();if(!res.ok)throw new Error(data.error);setNotice(message);formElement.reset();await loadList();if(selected)await loadDetail(selected);}catch(c){setError(c instanceof Error?c.message:"Upload failed");}finally{setBusy(false);}}
  if(!list)return <main className="presidents-badge-page"><p>Preparing President’s Badge applications…</p>{error&&<p className="error-banner">{error}</p>}</main>;
  if(detail&&selected)return <main className="presidents-badge-page">
    <div className="button-row"><button className="secondary" onClick={()=>{setDetail(null);setSelected(null);const u=new URL(window.location.href);u.searchParams.delete("application");window.history.replaceState({},"",u);}}>← All applications</button>{(detail.permissions.canManage || detail.member.email?.toLowerCase() === list.members.find(m=>m.id===detail.member.id)?.email?.toLowerCase()) && !["finalised","submitted","approved"].includes(detail.application.status) && <button className="danger-button" disabled={busy} onClick={()=>void deleteApplication()}>Delete application</button>}</div>
    <header className="presidents-hero"><div><p className="eyebrow">PRESIDENT’S BADGE APPLICATION</p><h1>{detail.member.name}</h1><p>{detail.member.rank} · {detail.member.squad}</p></div><span className={`status-chip status-${detail.application.status}`}>{statusLabels[detail.application.status]??detail.application.status}</span></header>
    {error&&<p className="error-banner">{error}</p>}{notice&&<p className="success-banner">{notice}</p>}
    <div className="presidents-grid">
      <section className="presidents-card presidents-card-wide live-preview-card"><div className="card-heading"><div><p className="eyebrow">LIVE PREVIEW</p><h2>Official form preview</h2></div><span className="status-chip">Page 1 of 5</span></div><p className="preview-help">This preview reflects unsaved edits. The final PDF keeps the official five-page layout and adds these values only in the mapped fields.</p><div className="official-preview"><div className="preview-brand">PRESIDENT’S BADGE APPLICATION <span>{detail.application.application_year}</span></div><div className="preview-grid"><div><small>Candidate</small><strong>{detail.member.name||"—"}</strong></div><div><small>Rank</small><strong>{detail.member.rank||"—"}</strong></div><div><small>Section / squad</small><strong>{detail.member.section} · {detail.member.squad}</strong></div><div><small>Birth date</small><strong>{draft.birthDate||"—"}</strong></div><div><small>NRIC</small><strong>{draft.nric||"—"}</strong></div><div><small>Captain</small><strong>{detail.officers.find(o=>String(o.id)===draft.captainId)?.name||"—"}</strong></div></div><div className="preview-awards"><div className="preview-awards-title">Awards and dates</div>{detail.eligibility.awards.length===0?<span>No awarded records yet.</span>:<div className="preview-award-list">{detail.eligibility.awards.map(a=><div key={`${a.award_code}-${a.awarded_at}`}><span>{a.award_name} <small>{a.level}</small></span><time>{a.awarded_at||"Date not recorded"}</time></div>)}</div>}</div></div></section>
      <section className="presidents-card"><h2>Eligibility</h2><p className={detail.eligibility.eligible?"complete-text":"warning-text"}>{detail.eligibility.eligible?"All linked requirements are met.":"Resolve the missing linked requirements before finalising."}</p><ul className="eligibility-list">{detail.eligibility.checks.map(check=><li key={check.label} className={check.met?"met":"missing"}><span>{check.met?"✓":"!"}</span>{check.label}</li>)}</ul></section>
      <section className="presidents-card"><h2>Candidate details</h2><p>These details appear on page 1 of the official form. NRIC is masked outside this authorised workflow.</p><form onSubmit={e=>{e.preventDefault();void run({action:"save_member_details",applicationId:selected,nric:draft.nric,birthDate:draft.birthDate},"Member details saved.");}}><label>NRIC<input name="nric" value={draft.nric} onChange={e=>setDraft({...draft,nric:e.target.value})} maxLength={20} required /></label><label>Birth date<input type="date" name="birthDate" value={draft.birthDate} onChange={e=>setDraft({...draft,birthDate:e.target.value})} required /></label><button className="primary" disabled={busy}>Save candidate details</button></form><form onSubmit={e=>upload(e,"upload_photo","Passport photo saved.")}><input type="hidden" name="memberId" value={detail.member.id}/><label>Passport photo<input type="file" name="file" accept="image/png,image/jpeg" required /></label><button className="secondary" disabled={busy}>Upload photo</button><small>{detail.member.passport_photo_object_key?"Photo on file":"Photo required"}</small></form></section>
      {detail.permissions.canManage&&<section className="presidents-card presidents-card-wide"><h2>1. Prepare application</h2><p>Choose the officers and meeting date first. The preview on the right updates immediately; saving stores these values for the official export.</p>{detail.application.status==="requested"&&<button className="primary" onClick={()=>void run({action:"claim",applicationId:selected},"You now own this application.")}>Take ownership</button>}<form className="form-grid" onSubmit={e=>{e.preventDefault();void run({action:"save",applicationId:selected,excoMeetingDate:draft.excoMeetingDate,awardsOfficerId:draft.awardsOfficerId,captainId:draft.captainId,includeCompanyStamp:(e.currentTarget.elements.namedItem("includeCompanyStamp") as HTMLInputElement).checked,notes:draft.notes,status:"preparing"},"Application saved.");}}><label>EXCO meeting date<input type="date" name="excoMeetingDate" value={draft.excoMeetingDate} onChange={e=>setDraft({...draft,excoMeetingDate:e.target.value})} /></label><label>Awards Officer<select name="awardsOfficerId" value={draft.awardsOfficerId} onChange={e=>setDraft({...draft,awardsOfficerId:e.target.value})}><option value="">Select Officer</option>{detail.officers.map(o=><option key={o.id} value={o.id}>{o.name} — {o.officer_rank||"Officer"}</option>)}</select></label><label>Captain<select name="captainId" value={draft.captainId} onChange={e=>setDraft({...draft,captainId:e.target.value})}><option value="">Select Captain</option>{detail.officers.map(o=><option key={o.id} value={o.id}>{o.name} — {o.officer_rank||"Officer"}</option>)}</select></label><label className="check-row"><input type="checkbox" name="includeCompanyStamp" defaultChecked={Boolean(detail.application.include_company_stamp)}/>Place saved company stamp on pages 2 and 5</label><label className="span-all">Officer notes<textarea name="notes" rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><button className="primary" disabled={busy}>Save preparation</button></form></section>}
      <section className="presidents-card presidents-card-wide"><h2>Assessments</h2><div className="assessment-grid">{detail.assessments.map(a=><article key={a.id}><h3>{a.assessor_type[0].toUpperCase()+a.assessor_type.slice(1)}</h3><span className="status-chip">{a.status.replaceAll("_"," ")}</span>{["parent","teacher"].includes(a.assessor_type)&&detail.permissions.canManage&&<><div className="segmented"><button type="button" className={a.completion_mode==="web"?"active":""} onClick={()=>void run({action:"set_assessment_mode",applicationId:selected,assessorType:a.assessor_type,mode:"web"},"Secure web assessment selected.")}>Secure web</button><button type="button" className={a.completion_mode==="paper"?"active":""} onClick={()=>void run({action:"set_assessment_mode",applicationId:selected,assessorType:a.assessor_type,mode:"paper"},"Official page will remain blank for paper completion.")}>Paper</button></div>{a.completion_mode==="web"&&<button className="secondary" onClick={async()=>{const result=await run({action:"invite_assessor",applicationId:selected,assessorType:a.assessor_type},"One-time assessment link created.");if(result?.assessmentUrl)setInvite(result.assessmentUrl);}}>Create 14-day link</button>}</>}</article>)}</div>{invite&&<div className="invite-box"><label>Private assessment link<input readOnly value={invite}/></label><button className="secondary" onClick={()=>void navigator.clipboard.writeText(invite)}>Copy link</button></div>}</section>
      {detail.permissions.canEndorse&&detail.assessments.find(a=>a.assessor_type==="captain")?.status!=="submitted"&&<section className="presidents-card presidents-card-wide"><h2>Captain assessment</h2><p>The selected Captain completes this inside the authenticated app. Applying a saved signature requires the Captain’s current password.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const qualities=["trustworthiness","respect","responsibility","fairness","caring","good_example","self_discipline","humility","attitude"];void run({action:"submit_captain_assessment",applicationId:selected,ratings:Object.fromEntries(qualities.map(q=>[q,Number(f.get(q))])),reasons:f.getAll("reasons"),remarks:f.get("remarks"),applySavedSignature:f.get("applySavedSignature")==="on",currentPassword:f.get("currentPassword")},"Captain assessment completed.");}}><div className="captain-ratings">{["trustworthiness","respect","responsibility","fairness","caring","good_example","self_discipline","humility","attitude"].map(q=><label key={q}>{q.replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase())}<select name={q} required defaultValue=""><option value="" disabled>Choose</option><option value="5">Excellent</option><option value="3">Good</option><option value="1">Average</option></select></label>)}</div><fieldset><legend>Recommendation reasons — choose at least two</legend>{["Shows consistent character","Serves others willingly","Demonstrates leadership","Is dependable","Is ready for the President’s Badge"].map(reason=><label className="check-row" key={reason}><input type="checkbox" name="reasons" value={reason}/>{reason}</label>)}</fieldset><label>Remarks<textarea name="remarks" rows={3}/></label><label className="check-row"><input type="checkbox" name="applySavedSignature"/>Apply my saved signature to pages 2 and 5</label><label>Current password (required only when applying signature)<input type="password" name="currentPassword" autoComplete="current-password"/></label><div className="button-row"><button className="primary" disabled={busy}>Complete Captain assessment</button></div></form><form onSubmit={e=>upload(e,"upload_signature","Your reusable signature was stored privately.")}><label>My signature image<input type="file" name="file" accept="image/png,image/jpeg" required/></label><button className="secondary" disabled={busy}>Save my signature</button></form></section>}
      <section className="presidents-card"><h2>Camp history</h2><ul>{detail.camps.map(c=><li key={c.id}>{c.camp_year} · {c.camp_level} · {c.description}</li>)}</ul>{detail.permissions.canManage&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"save_camp",applicationId:selected,year:f.get("year"),level:f.get("level"),description:f.get("description")},"Camp history added.");}}><label>Year<input type="number" name="year" min="1950" max="2100" required/></label><label>Level<select name="level"><option>CO</option><option>ST</option><option>NAT</option><option>INT</option></select></label><label>Description<input name="description" maxLength={60}/></label><button className="secondary" disabled={busy}>Add camp</button></form>}</section>
      <section className="presidents-card"><h2>Finalised PDF versions</h2>{detail.versions.length===0?<p>No locked version yet.</p>:<ul>{detail.versions.map(v=><li key={v.id}>Version {v.version_number} · {new Date(v.created_at).toLocaleDateString()} <a href={`/api/presidents-badge/download?applicationId=${selected}&versionId=${v.id}`}>Download</a>{v.superseded_at&&<small> Superseded</small>}</li>)}</ul>}{detail.permissions.canManage&&<div className="button-row">{!["finalised","submitted","approved"].includes(detail.application.status)&&<button className="primary" disabled={busy} onClick={()=>void run({action:"finalise",applicationId:selected},"A locked PDF version was created.")}>Validate and finalise PDF</button>}{detail.application.status==="finalised"&&<><button className="secondary" onClick={()=>void run({action:"reopen",applicationId:selected},"Application reopened; the previous PDF remains immutable.")}>Reopen as new version</button><button className="primary" onClick={()=>void run({action:"mark_submitted",applicationId:selected},"External submission recorded.")}>Mark submitted</button></>}</div>}</section>
      {detail.permissions.canOutcome&&<section className="presidents-card presidents-card-wide"><h2>External BBM outcome</h2><p>Finalising or submitting never awards the badge. Only a confirmed BBM approval updates the award record.</p>{detail.outcomes.length>0&&<ul>{detail.outcomes.map(outcome=><li key={outcome.id}>{outcome.outcome} · {outcome.outcome_date} {outcome.reference&&`· ${outcome.reference}`} {outcome.returned_document_object_key&&<a href={`/api/presidents-badge/download?applicationId=${selected}&outcomeId=${outcome.id}`}>Download supporting document</a>}</li>)}</ul>}<form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"record_outcome",applicationId:selected,outcome:f.get("outcome"),outcomeDate:f.get("outcomeDate"),reference:f.get("reference"),notes:f.get("notes"),confirmed:f.get("confirmed")==="on"},"External outcome recorded.");}}><label>Outcome<select name="outcome" required><option value="">Choose outcome</option><option value="returned">Returned</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><label>Decision date<input type="date" name="outcomeDate" required/></label><label>BBM reference<input name="reference"/></label><label className="check-row"><input type="checkbox" name="confirmed"/>I confirm this is an external BBM decision</label><label className="span-all">Notes<textarea name="notes" rows={3}/></label><button className="primary" disabled={busy}>Record outcome</button></form>{detail.outcomes.length>0&&<form onSubmit={e=>upload(e,"upload_outcome_document","Supporting BBM document stored privately.")}><input type="hidden" name="applicationId" value={selected}/><label>Supporting or returned document<input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required/></label><button className="secondary" disabled={busy}>Upload supporting document</button></form>}</section>}
    </div>
  </main>;
  return <main className="presidents-badge-page"><header className="presidents-hero"><div><p className="eyebrow">PEOPLE → AWARDS</p><h1>President’s Badge Applications</h1><p>Prepare the official five-page AWA-SR01/2010-9 form without changing its original artwork.</p></div></header>{error&&<p className="error-banner">{error}</p>}{notice&&<p className="success-banner">{notice}</p>}{!list.r2Available&&<p className="warning-banner">Private R2 document storage is not connected. Applications can be prepared, but official templates and completed PDFs require the DOCUMENTS binding.</p>}
    <div className="presidents-grid">
      <section className="presidents-card"><h2>Start an application</h2><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const result=await run({action:"create",memberId:f.get("memberId")},"Application created.");if(result?.applicationId)void loadDetail(result.applicationId);}}><label>Senior Section member<select name="memberId" required><option value="">Choose member</option>{list.members.map(m=><option key={m.id} value={m.id}>{m.name} — {m.rank}</option>)}</select></label><button className="primary" disabled={busy}>Start application</button></form></section>
      {list.permissions.canTemplate&&<section className="presidents-card"><h2>Exact official template</h2><p>{list.template?`${list.template.form_code} verified and stored privately.`:"Upload the exact official PDF. Similar-looking or revised files are rejected."}</p><code className="hash-code">{list.profile.sha256}</code><form onSubmit={e=>upload(e,"upload_template","Official template verified and stored privately.")}><label>Official PDF<input type="file" name="file" accept="application/pdf" required/></label><button className="secondary" disabled={busy}>Verify and upload</button></form></section>}
      {list.permissions.canManage&&<section className="presidents-card"><h2>Official company details</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"save_settings",companyNumber:f.get("companyNumber"),companyName:f.get("companyName"),state:f.get("state")},"Official company details saved.");}}><label>BB company number<input name="companyNumber" maxLength={12} defaultValue={list.settings?.company_number??""}/></label><label>Official company name<input name="companyName" maxLength={44} defaultValue={list.settings?.official_company_name??""}/></label><label>Malaysian state<input name="state" maxLength={30} defaultValue={list.settings?.malaysian_state??""}/></label><button className="secondary" disabled={busy}>Save company details</button></form>{list.permissions.canTemplate&&<form onSubmit={e=>upload(e,"upload_stamp","Optional company stamp stored privately.")}><label>Optional company stamp<input type="file" name="file" accept="image/png,image/jpeg" required/></label><button className="secondary" disabled={busy}>Upload stamp</button></form>}</section>}
      {list.permissions.canManage&&<section className="presidents-card"><h2>Annual compliance dates</h2><p>These dates populate page 2 for the selected application year.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({action:"save_compliance",year:f.get("year"),brigadeDuesDate:f.get("brigadeDuesDate"),rosReturnDate:f.get("rosReturnDate"),statisticsReturnDate:f.get("statisticsReturnDate")},"Annual compliance dates saved.");}}><label>Reporting year<input type="number" name="year" min="2000" max="2100" defaultValue={new Date().getFullYear()} required/></label><label>Brigade Dues paid<input type="date" name="brigadeDuesDate"/></label><label>ROS Return submitted<input type="date" name="rosReturnDate"/></label><label>Statistics Return submitted<input type="date" name="statisticsReturnDate"/></label><button className="secondary" disabled={busy}>Save compliance dates</button></form></section>}
      <section className="presidents-card presidents-card-wide"><h2>Applications</h2>{list.applications.length===0?<div className="empty-state"><h3>No applications yet</h3><p>Start one for an eligible Senior Section member.</p></div>:<div className="application-list">{list.applications.map(a=><button key={a.id} onClick={()=>void loadDetail(a.id)}><span><strong>{a.member_name}</strong><small>{a.rank} · {a.application_year}</small></span><span className={`status-chip status-${a.status}`}>{statusLabels[a.status]??a.status}</span></button>)}</div>}</section>
    </div>
  </main>;
}
